### ISSUE TITLE
QuickPulseTelemetryModulere reports real machine name (PII issue)

### ISSUE THREAD

**Issue by mediawolf** [Microsoft/ApplicationInsights-dotnet#1061]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Add QuickPulseTelemetryModule to ApplicationInsights.config

##  Actual Behavior
QuickPulseTelemetryModule sends real machine name.
I've implemented custom processor, which is executed before TransmissionProcessor and removes machine name:
```
            context.GetInternalContext().NodeName = ".";
            context.Cloud.RoleInstance = ".";
```
But still, real machine name appears in Live Metrics Stream.

## Expected Behavior
API should allow to define PII stuff in a central place so later library facilities can read it from there.

## Version Info 
SDK Version : 2.8.1
.NET Version :	4.7.1
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VS
OS : Win10
Hosting Info (IIS/Azure WebApps/ etc) : desktop application

**Comment by Dmitry-Matveev** [comment]
@mediawolf , Quick Pulse a.k.a. Live Metrics does not store the data processed - it's entirely in memory and is discarded once the browser is closed. Is it still a privacy concern because an engineer with the access to the application telemetry can learn machine name?
If yes, you can set your Telemetry Processor before QuickPulse processor in the Telemetry Processors Chain, this will essentially remove those names before they can be used.

If QuickPulse reads machine name from the other sources and reports to light up custom configuration or some other feature, then, I guess, it's not easy to remove it in such a case. @netghost, would you know an owner of Live metrics nowadays, so we can add them to this thread?

**Comment by mediawolf** [comment]
@Dmitry-Matveev  I thought that Quick Pulse data goes thru the same channel as all other telemetry so I've put my processor last. But, indeed, Quick Pulse module uses own channel for transferring data. Putting my processor before Quick Pulse works well. Thank you.

**Comment by mediawolf** [comment]
Real computer name appears in "Live Metrics Stream" as soon as I start my application. That happens before any telemetry data is reported. Thus my processor can only patch live data but not a data that is passed during connection establishment.

**Comment by Dmitry-Matveev** [comment]
@tokaplan , @netgh0st, is there any workaround to obfusccate machine name from in Live Metrics for the cases where Telemetry Initializer does not work?

**Comment by tokaplan** [comment]
What's the nature of the problem? Is the problem that the name of the physical machine leaves the box at all, or is it that it's shown in the Live Metrics Stream UX?

Environment.MachineName will always be sent to the backend in the current implementation, you can't affect that behavior.

In order for you to hide the machine name from Live Metrics Stream UX, I _think_ you can implement a telemetry **_initializer_** (not processor) which sanitizes context.Cloud.RoleInstance. Make sure it's the last one in the chain.

**Comment by mediawolf** [comment]
@tokaplan Both are problems.
My processor assigns own device id (no PII) to CloudInstance property for 'normal' telemetry which I would want to use for live data too, thus both data sources could be correlated later.
Thanks. Custom initializer works with patching both CloudInstance and Internal.NodeName.
