### ISSUE TITLE
How to capture and report ASMX exceptions?

### ISSUE THREAD

**Issue by mikevanoo** [microsoft/ApplicationInsights-dotnet#1099]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create a new, empty "ASP.NET Application (.NET Framework)"
2. Add a new ASMX web service
3. Add code to throw an exception from the WebMethod
4. Add a Global.asax file
5. Add the global error handling code from https://docs.microsoft.com/en-gb/azure/azure-monitor/app/asp-net-exceptions#web-forms to the Application_Error event in the Global class
6. Add AppInsights to the site
7. Run the site and hit the web method

##  Actual Behavior
The code in the global error handler is NOT hit and the exception is sent to AppInsights as a normal HTTP request with a 500 status code.

## Expected Behavior
The code in the global error handler is hit and the exception is sent to AppInsights as a "real" exception.

## Version Info 
SDK Version : 2.9.1
.NET Version :	4.7.1 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10 (1703)
Hosting Info (IIS/Azure WebApps/ etc) : IISExpress

## Details
Create this issue from https://github.com/MicrosoftDocs/azure-docs/issues/6144

I believe this happens because the ASMX framework handles the exception internally to enable it to return a SOAP fault. It would be good if AppInsights could instrument this and capture the exception auto-magically.

**Comment by Dmitry-Matveev** [comment]
Most likely, as per your suggestion as well, Application_Error handler wasn't hit because the exception was handled internally by the platform. Therefore, Application Insights was not notified about the exception and no exception telemetry is produced.

I'm not sure about the best way to capture ASMX handled exception, if there is one - AI's TrackException() should be plugged into that code.

Alternatively, there is [an experimental feature in AI](https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/212) that tracks first-chance exceptions and sends an example/aggregated info about them to AI. You can try it out by adding `<Add Type="Microsoft.ApplicationInsights.WindowsServer.FirstChanceExceptionStatisticsTelemetryModule, Microsoft.AI.WindowsServer"></Add>` entry to your `applicationinsights.config` file under `<TelemetryModules>`.

@SergeyKanzhelev, I guess that's all one needs to do to try out Exception Stats, right?
