### ISSUE TITLE
What happened to issue 1102 ?

### ISSUE THREAD

**Issue by pharring** [microsoft/ApplicationInsights-dotnet#1150]
Issue #1102 is gone from this repo.
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1102
This issue discussed an unmanaged memory leak in Application Insights and is linked from the eventual fix in .NET Core CLR.
Was it deleted (by the owner?) or flagged for a policy violation?
Can the admins take a look, please?

**Comment by cijothomas** [comment]
It looks like only admins can delete an issue....

**Comment by cijothomas** [comment]
https://help.github.com/en/articles/deleting-an-issue
Collaborators do not receive a notification when you delete an issue. When visiting the URL of a deleted issue, collaborators will see a message stating that the issue is deleted. People with admin or owner permissions in the repository will additionally see the username of the person who deleted the issue and when it was deleted.

I have admin right to this repo, but i am also getting 404 page not found , and nothing about the issue being deleted...

**Comment by cijothomas** [comment]
@SergeyKanzhelev @Dmitry-Matveev anyone we can ping to find what happened.

**Comment by SergeyKanzhelev** [comment]
wow. maybe GitHub glitch that will get resolved? Few days back I had this for some issues in different org.

**Comment by SergeyKanzhelev** [comment]
It is back up now https://github.com/microsoft/ApplicationInsights-dotnet/issues/1102

![image](https://user-images.githubusercontent.com/9950081/58649087-1342fe00-82c0-11e9-84f4-f5366cec93c5.png)

**Comment by SergeyKanzhelev** [comment]
Perhaps it was some GitHub issue
