### ISSUE TITLE
Anomaly Sampling Model

### ISSUE THREAD

**Issue by dylan-asos** [microsoft/ApplicationInsights-dotnet#1208]
Just seeing if there's any interest in the following. As part of running at high scale, we've enabled adaptive sampling but the teams using the telemetry to support have found some operations sampled out that would have helped them perform RCA. We require a model where we sample on the happy path and capture more data on the failures - we've come up with an 'Anomaly Sampling' model that allows us to:

- We always capture a full telemetry journey for any operation that

1. ends in an exception
2. ends in a non-success status code
3. ran for too long (greater than x)
 
- We always capture full telemetry for any dependencies that
1. Weren’t successful or
2. Ran for greater than x
 
- We can selectively choose to include certain ‘custom events’ to always capture full journey
 
- We have a set of metrics that run across all our API endpoints that give us
1. Response times, split by status code
2. Count of operations
 
- We sample more aggressively on all operations that were successful / ran quickly

We wanted a default set of rules to enable the above, but allow teams to customise as they required, so we went with a 'rules based approach' where you can configure the detection settings that control if all telemetry points generated by a journey should remain unsampled. The API is like so, 

```
public void ConfigureServices(IServiceCollection services)
{
   services.AddApplicationInsightsTelemetry(new ApplicationInsightsServiceOptions()
   {
         InstrumentationKey = "demo-demo",
         EnableAdaptiveSampling = false
   });

   var anomalyDetectionSettings = new AnomalyDetectionSettings()
   {
      SampleIfException = false,  // Never sample if a journey generated an exception
      AlwaysCaptureEventCodeNames = { "Timeout", "SomeInterestingEvent" } // neven sample if the journey generated any of these custom events
   };

   // Never sample where any dependency call to Redis ran for more than 2 seconds
   anomalyDetectionSettings.DependencyNonSamplingRules.Add(new NonSamplingRule<DependencyTelemetry>("Slow Redis Dependencies", 
      telemetry => telemetry.Target == "Redis" && telemetry.Duration > TimeSpan.FromSeconds(2)));

   // Never sample requests that end in a 500
   anomalyDetectionSettings.RequestNonSamplingRules.Add(new NonSamplingRule<RequestTelemetry>("Server Errors",
      telemetry => Convert.ToInt32(telemetry.ResponseCode) > 499));

   services.UseAnomalyDetectionSampling(anomalyDetectionSettings);

   services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
```

We're aware that in a failing scenario we would end up generating a lot of telemetry, but we're happy to pay for that hopefully rare scenario for the advantage of always capturing the strange/weird behaviour that might otherwise be hidden from us through sampling.

If there's any interest, happy to create a fork on this repo or make available as a separate package.

**Comment by cijothomas** [comment]
@Dmitry-Matveev Can you respond to this? You are sampling expert :)

**Comment by Dmitry-Matveev** [comment]
@dylan-asos , in a scenario when exception or failed/slow dependency happens deep in the request pipeline after other telemetry items were already generated and passed through initializers and are in buffer - how do you make them sampled in back if they were sampled out? Otherwise the transaction will contain main request and only failed components inside, or components that come after the failed one since you'd know at that moment to keep everything for that operation ID?

On the other hand, I think that there is another sampling paradigm being considered in OpenTelemetry initiative (@SergeyKanzhelev to comment) and the existing sampling mechanism might be replaced in the mid-term future.

**Comment by dylan-asos** [comment]
@Dmitry-Matveev we keep track of the telemetry items being generated as part of the request and make the decision to sample based on the rules/results of those deeper telemetry items. If *any* of the telemetry items indicate they shouldn't be sampled, we skip the sampling processor and send everything through.

We've simply inherited from AdaptiveSamplingTelemetryProcessor and perform our custom logic here, either bypassing the sampling logic or allowing it to be sampled as normal - It's actually not much code to achieve this. Performance wise - the impact is negligible. We're running this in an API that averages 800-1000RPS and creates about 15 telemetry items per request and haven't noticed any adverse behaviour so far. 

We were somewhat inspired by the Dynamic Sampling approach described in this article - https://read.acloud.guru/why-you-cant-effectively-debug-your-modern-systems-with-dashboards-57fe3ecd26bf, particularly this paragraph.

“This concept is sometimes confusing to people because they think you’re just taking a percentage across the board, and you’re not. The idea here is to store common things a small percentage of the time, and store uncommon things a very high percentage of the time or all the time.”

I'll make the code available in github so you can see the approach we've taken, I'll reply back with the repo link

**Comment by dylan-asos** [comment]
Repo is here if you want a look - https://github.com/dylan-asos/ApplicationInsights.AnomalyDetectionSampling. (It needs a bit of refining, but shows what the API might look like)

**Comment by Dmitry-Matveev** [comment]
@dylan-asos , sorry it took a while to get back here.

This approach seem to work fine in the context of the single service as it relies on the fact that Request Telemetry arrives last to the Telemetry Processors to wrap up the transaction within the service and you can store all associated telemetry items in a "journey" until this moment.

You would need to send some sort of the flag down the services chain and back up the chain to make sure that the telemetry on service before and after you is sampled in as well to have a cross-services transaction sampled in. This is a little bit more complicated, because the moment the exception happens and you know you would like to sample the data in can happen after you made the outgoing call to another service, so there will be no way to update its headers and downstream service won't know to sample their telemetry in as well (you may need that data because it's likely that the response from downstream service had caused an exception later in your service).

@SergeyKanzhelev who may know how are we approaching this in Open Telemetry and whether it already has a spec or some implementation of the sampling that may consider anomalies tracking and sampling flag propagation.

**Comment by dylan-asos** [comment]
@Dmitry-Matveev thanks for detailed response - yes, didn't consider the distributed services part of this as was looking at a service in isolation, can see that would be a challenging problem to address. :)

I do think that the ability to tweak and set different sampling rates for different conditions would be a powerful addition to the solution, allowing engineers to really fine tune the data they produce. Can park this, will leave repo linked above in place for anyone who stumbles on this thread, sounds like some interesting stuff coming soon.
