### ISSUE TITLE
Operation Id and ParentId are rearranged or wrong

### ISSUE THREAD

**Issue by nosalan** [microsoft/ApplicationInsights-dotnet#1254]
## Repro Steps
1. Make a HTTP request to Kestrel with header: "Request-Id" : "CCCCC"
2. Kestrel will fill in the `Activity.Current` object:
![image](https://user-images.githubusercontent.com/2273250/67076603-c0de7d00-f18d-11e9-87ef-fba013e891de.png)
3. Application Insights are configured (`UseApplicationInsights()`) so all requests are sent there. Additionally custom event is being reported. What I see in Azure -> Logs (Analytics) is following:

**For request:**
![image](https://user-images.githubusercontent.com/2273250/67077017-99d47b00-f18e-11e9-8c3f-e98c65c7e9b6.png)

**For custom event:**
![image](https://user-images.githubusercontent.com/2273250/67077107-d1dbbe00-f18e-11e9-9d70-9fa521be069d.png)

Why is this like that? For `request` both operationId and parentOperationId are the same. For `customevents` reported withing this context, these two are flipped. Totally can't understand this, this makes correlating events really hard. Is this a bug or I don't know something? What I would expect is Id and ParentId to be consistend across everything.

## Version Info 
SDK Version : "2.2.6"
.NET Version :	netcoreapp2.2 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : None
OS : Ubuntu
Hosting Info (IIS/Azure WebApps/ etc) :Kestrel

**Comment by cijothomas** [comment]
This is expected behavior.
When you send a request with "Request-Id" header "CCCCC", then "CCCCC" is used by hosting layer to generate its own ids which will be |CCCCC.random_ . And application insights respects it as well.

Why is this difficult to correlate? Application Insights UI should show this correlated correctly, and so can you if you use another tool for correlation.

All telemetry produced in the context of this Request will have same operation id. - "CCCCC", so they can be logically linked together.
Every telemetry generated in the context of this Request will have their operation.ParentId set to the ID of the RequestTelemetry.
The RequestTelemetry itself has parentID of "CCCCC" and its parent is external (extracted from request-id header)

This is the doc about correlation:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation

**Comment by nosalan** [comment]
> Every telemetry generated in the context of this Request will have their operation.ParentId set to the ID of the RequestTelemetry.

My screenshots show that it isn't true. For `requests` the operation_ParentId is different than for `customEvents` despite both being generated in the same context.
