### ISSUE TITLE
TelemetryClient.Flush does not give errors with invalid InstrumentationKey

### ISSUE THREAD

**Issue by Metrowerks** [microsoft/ApplicationInsights-dotnet#1256]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Run below code
```
         var configuration = new TelemetryConfiguration
            {
                InstrumentationKey = "<some invalid key>",
                TelemetryChannel = new Microsoft.ApplicationInsights.Channel.InMemoryChannel()
            };
            var telemetryClient = new TelemetryClient(configuration);
            telemetryClient.Context.Operation.Id = Guid.NewGuid().ToString();
            telemetryClient.Context.Operation.Name = "Op Name";
            telemetryClient.TrackEvent("Testing App Insights SDK", new Dictionary<string, string> { { "TestEvent", "TestValue" } });
            telemetryClient.TrackTrace("App Insights Test");
            telemetryClient.Flush();
```

##  Actual Behavior
- Flush() went through with no errors. 
  - This gave our API the impression that everything was OK and 200 would be returned, which was misleading.

## Expected Behavior
- Exception should have been thrown if InstrumentationKey is invalid

## Version Info 
SDK Version : 2.11
.NET Version :	netcoreapp2.0 						
Hosting Info (IIS/Azure WebApps/ etc) : IIS

**Comment by TimothyMothra** [comment]
Hello @freebird8x, Thanks for reporting this.
Can you please describe how your ikey was invalid?

We've been having an internal discussion about this subject for the last couple of weeks. 
Historically, a decision was made some time ago to NOT crash an application based on the ikey.
We are revisiting this.

Our ingestion service does return some metadata about ikey and we emit this in the logs. 
https://github.com/microsoft/ApplicationInsights-Home/tree/master/Samples/ETW#tools-to-collect-etw

**Comment by freebird8x** [comment]
Hi, the key can be anything. It can be an empty string and Flush still went through with no errors. For our case, mistake can be made when we are switching deployment environment (i.e. dev, acceptance, etc.) and the key is not updated correctly, or someone uses a temporary environment but forgets to roll back the key after the environment is removed.

This is a critical bug for us. We have a buffer for pushing logs to App Insights and as long as the push returns 200, we clear the buffer. So if for any reason, a mistake is made on the iKey, we will be losing lots of data without knowing.

On another related issue, Flush() doesn't return any error code or response right now and if anything happens inside it, like a crash, the exceptions will be swallowed and we will also return 200, which will cause the same data lost problem.

I'm with you guys that Flush() is better off not to crash the code, but there should be some returned error code or response to indicate a successful push. Otherwise, it will be extremely difficult to QA the code.

**Comment by TimothyMothra** [comment]
Yeah, our Flush method does not meet expectations for a lot of scenarios. It's on the very top of our backlog to be redesigned, but I don't have an estimate at this time. Thank you again for reporting this scenario.

Curious that you're managing your own buffer, have you evaluated our `ServerTelemetryChannel`? We use our own buffer and manage retries. https://docs.microsoft.com/en-us/azure/azure-monitor/app/telemetry-channels#built-in-telemetry-channels

**Comment by freebird8x** [comment]
We're using the ServerTelemetryChannel but our case is more complicated as the buffer we maintain is on client's machine, which is on internal network, while the Flush() happens on an API that does the actual talks to Azure. So we pretty much gets the relayed response from the API to clear the local buffer.

I hope it will be fixed soon as enterprises like us are considering more Azure solutions but things like this really held us back.

**Comment by cijothomas** [comment]
Whether ikey is valid or not - Visual Studio experiences are still light up, thats probably the reason why it was decided not to throw if ikey is invalid.

**Comment by TimothyMothra** [comment]
We're really talking about three different problems here...


**1. Invalid Ikey.**
I'm actively working on this, and it should be delivered in the 2.12 stable release scheduled for early December.
Adding an exception to Flush() isn't going to solve this problem.
Instead we'll likely throw exceptions from the TelemetryConfiguration.InstrumentationKey property for very specific cases (ex: null, empty, illegal characters).
You may track this progress here: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1260


Reviewing your description:
> For our case, mistake can be made when we are switching deployment environment (i.e. dev, acceptance, etc.) and the key is not updated correctly, or someone uses a temporary environment but forgets to roll back the key after the environment is removed.

I would like to politely suggest that you consider deployment scripts to remove the human error from your environment configurations. 
Many of our ASP.Net customers use an environment specific web.config transform to set the ikey. 
Me personally, I'm not a NetCore developer so I don't know the correct alternative for your project type but if you need some help I can try to find someone who is familiar with this subject.





**2. Flush**
Our SDK does not validate your ikey, but our ingestion service does. 
The ingestion service returns various HTTP response codes for your specific problems (ex: data cap exceeded, throttling, invalid ikey).

As you've stated, you're not receiving these response codes and cannot programmatically respond to them.

Adding exceptions to the Flush method will not solve your problem here.
Our telemetry channels send data constantly on an async background thread. Flush is only going send the current batch in the channel's buffer.



**3. TelemetryChannel & service Http response codes.**


I don't know how to solve this problem without rearchitecting a significant portion of the product. I will need to discuss this with our team, as solving this specific problem is not on our backlog and we're not ready to commit to this.
Our channels transmit data on background async threads so there is no convenient way to emit these response codes.
If our channel starts to throw exceptions, this would have unintended side effects so I don't believe this is the correct resolution.
Thinking out loud, maybe we could implement an optional event handler to the channel for you to subscribe to Http response codes, but honestly, I'm not certain what value this will provide.
I would like to hear your thoughts/ideas on this.


In your code sample, you referenced the `InMemoryChannel`. 
You raised several concerns about losing data, and for this reason, we do recommend using the `ServerTelemetryChannel` which will persist data to your file system in the event of service errors.
You replied that you're already using the `ServerTelemetryChannel` in your production code so I think you're doing the right thing here.


**As a workaround, you can subscribe to the ETW event logs that both of our channels emit.**


`InMemoryChannel` implementation
- https://github.com/microsoft/ApplicationInsights-dotnet/blob/7633ae849edc826a8547745b6bf9f3174715d4bd/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L163-L200

`ServerTelemetryChannel` implementation
- https://github.com/microsoft/ApplicationInsights-dotnet/blob/7633ae849edc826a8547745b6bf9f3174715d4bd/BASE/src/ServerTelemetryChannel/Implementation/TransmissionSender.cs#L173-L192

ETW resources
- https://github.com/microsoft/ApplicationInsights-Home/tree/master/Samples/ETW

Code sample
- https://github.com/microsoft/ApplicationInsights-Home/blob/master/Samples/ETW/TraceEventUtility.cs

**Comment by withrocks** [comment]
@TimothyMothra, @cijothomas 

I have a use case where I want to log only once from the terminal and then flush and exit the process, and I would like to write an error to `stdout` if the logging was not successful.

Because of this I'm using `InMemoryChannel` and flushing directly afterwards. I saw that @TimothyMothra suggested that we can subscribe to the ETW event logs, but I'm not sure how to do that.

As I understand it, the following should suffice:

```
... // (1) Enable verbose logging in CoreEventSource

Trace.Listeners.Add(new ConsoleTraceListener()); // (2)

// (3) log
```

It's the (1) step that I'm unsure about. What's the right way to configure verbose logging?

Thanks!

**Comment by withrocks** [comment]
@TimothyMothra  Update: After reading the code properly, I now see that I'm not really looking for how to enable verbose logging, but just being able to listen to the log written in `CoreEventSource.Log.TransmissionStatusEventFailed(ex);`.

I assumed that adding the console trace listener to `Trace.Listeners` was enough to listen to all messages traced in the process, but I guess that's not enough. I wonder if you could guide me in the right direction?
