### ISSUE TITLE
Question about tracking events in Application Insights

### ISSUE THREAD

**Issue by erndob** [microsoft/ApplicationInsights-dotnet#1271]
I'm trying to port my TelemetryClient usage to ILogger with ApplicationInsightsProvider.

I have a lot of TrackEvent logging. 

I see that the current implementation, always uses  TraceTelemetry, and never uses EventTelemetry, yet it does populate the EventName property if the EventId is provided. 

My question is, is there any actual difference from ApplicationInsights perspective if I change all EventTelemetry to TraceTelemetry, but with same EventName property?

I guess it would be possible to code the case, `if message is empty but the EventId object has a name, create a EventTelemetry instead`. Is that something we could add?

**Comment by Dmitry-Matveev** [comment]
If the existing customers are not affected and new customers are not getting this feature by default, the risk of supportability cost increase is low and PR should be easy to accept. However, if we are doing this, it also means that the feature is not built for the major public consumption, but for "case-by-case" use. With that, we can simply go the way @SergeyKanzhelev suggested - use extensibility point rather than changing the SDK itself.

I see the value in the suggestion, so I can see why making this public and default can warm the hearts of a certain customer base while confusing the other :).

However, due to supportability concerns I outlined above, I would not recommend simply implementing this conditional logic as one-off PR and shipping right away - we would need to go through the whole process of feature evaluation and involve PM team into the conversation.

**Comment by amigup** [comment]
@Dmitry-Matveev - One could write the extended method but if there are many customers who need the same feature then it would be pure candidate that feature should go to SDK.

As per I can tell, **event** is one of the core feature provided by Application Insights and not having of it part of integration by SDK means demotivating users not to use out of box feature if they want to rely on `Microsoft.Logging.Extensions` packages. Writing own implementation or injecting both `ILogger` and `TelemetryClient` can be done but are those the graceful solution or those are workaround?

My suggestion that the SDK can introduce another method name `AddApplicationInsightsEventTelemetry` to enable the EventTelemetry so that only those customers who really need that will call that method in app builder pipeline. 

Finally the key of any product/SDK is documentation which is good for `Application Insights` so far; so  having a situation where customer can get confused due proposed requirement, may seldom come.

**Comment by johnib** [comment]
@Dmitry-Matveev how is my suggestion different than how exceptions are being handled by the the SDK?

There's a feature flag for exceptions, that makes the SDK send exceptions as _Exception_ item type instead of trace.

All I suggest, is do the same for custom events.

We really want and need this, and the alternatives are not as good as this one.
This can be implemented quite quickly, respecting your concerns as well -- and we'd really appreciate if that happens.

**Comment by Dmitry-Matveev** [comment]
Adding exceptions to ILogger was just following the trend of every other AI logging solution and customers were well educated on this, therefore no issue.

Adding exceptions for the first time was just as controversial as adding events today. That's why I mentioned that in general if we move cautiously with opt-in in mind and clear documentation + we have a scenario we're trying to address rather than one-off fix, we can proceed with this change. 

Having a valid use case will also help to drive proper integration discussions with OpenTelemetry (which only supports logs ATM).

We already have people on the thread suggesting a contribution, so I think we should look into this contibution as soon as we understand the actual use-case / scenario (I guess we already agree on opt-in model to start with).

**Comment by aforank** [comment]
I think ApplicationInsightsProvider should not only support events but also other log types such as dependency, requests, page view and availability. This can be easily achieved by writing new extension methods like LogDependency or LogEvent. We can use Event Id to differentiate among each log type and passing any custom data using TState object of ILogger. 

I am happy to contribute if the team is willing accept. :)

**Comment by cijothomas** [comment]
@aforank  We certainly don't have to extract dependency, requests etc, from a logging API. Its technically feasible, but does not fit the overall schema for having Requests/Dependencies.

The discussion about Traces is still open - no active work is happening in this issue right, as we want to align with OpenTelemetry standard for logging and are waiting for OpenTelemetry to finalize their logging API. Its quite possible that OpenTelemetry will simply suggest using Ilogger for .net, but I dont know yet.
