### ISSUE TITLE
First heartbeat sent after 15 minutes instead of configured interval

### ISSUE THREAD

**Issue by xavierdecoster** [microsoft/ApplicationInsights-dotnet#1298]
It appears that the very first heartbeat is sent after `15 minutes`, which is the default built-in heartbeat interval, even when a different interval is configured. Every other subsequent heartbeat will respect the configured interval.

SDK version used: `2.10.0`

Attached some code that reproduces the issue.

Expected behavior: heartbeats start after the very first minute (as configured)
Actual behavior: heartbeats only start after 15 minutes (default interval)

[ConsoleApp1.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/3837607/ConsoleApp1.zip)

**Comment by cijothomas** [comment]
Its a bug/limitation as setting interval does not alter the current timer, which is triggered upon initialize. 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Managed/Shared/Extensibility/Implementation/Tracing/HeartbeatProvider.cs#L91

Use the following workaround:
Basically, don't use .Active, instead create DiagnosticTelemetryModule by yourself, so that you can interval **before** initializing it.

static void Main(string[] args)
        {

            var tc = new TelemetryConfiguration("ikey");
            var diagModule = new DiagnosticsTelemetryModule();
            diagModule.HeartbeatInterval = TimeSpan.FromSeconds(30);
            diagModule.Initialize(tc);
            
            while(true)
            {

            }
        }

(Modify example as per your requirement, but this should give you the idea)

**Comment by xavierdecoster** [comment]
@cijothomas does the call to `new TelemetryConfiguration("ikey")` still consider the `applicationinsights.config` file? Or should we rely on `TelemetryConfiguration.CreateDefault()` instead, and then set `TelemetryConfiguration.InstrumentationKey` on that instance?

**Comment by cijothomas** [comment]
new TelemetryConfiguration("ikey") wont consider ai.config.
