### ISSUE TITLE
Http status code >=400 returned from middle ware is not showing as response codes in failure section of the application insights telemetry

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#1402]
Reported by @sajibcefalo: https://github.com/Microsoft/ApplicationInsights-Home/issues/239

>I have an asp .net web api application. There is a custom middleware placed after telemetry middleware before the asp. net web api. In some cases, the middleware return http status code 429. I have gone to the application insights failure section and Http status code 429 is not listed in top 3 response codes. I have also tried to return other error code such 401 but nothing is listed in response code. I guess if we return any http status code other than 200 from middleware it is always listed as http status code 200.
>I have also returned 400+ http status code from web api action method, filter and delegate handler. In each case, in application insights failure section's Top 3 response codes section, the status code is enlisted.
>Is this expected behavior? I am intended to show http status code 400+ returned from middleware in top 3 response code. How can I do it?

**Comment by sajibcefalo** [comment]
@TimothyMothra Do you know when the bug will be resolved?

**Comment by TimothyMothra** [comment]
Hi @sajibcefalo, someone is looking into this, but I don't have an update or timeline to share.
I wanted to reply so you know we're not ignoring this, and I'm trying to get you a substantive answer.

**Comment by TimothyMothra** [comment]
I got a deeper explanation of what's going on here.
This behavior is a consequence of having multiple HttpModules. 
Since we don't control the execution order, our SDK can log end-request traces before another module has completed it's handling of a request, which causes the discrepancy that you're seeing.

**The root cause here is that our sdk does not provide native support for OWIN.**
@Dmitry-Matveev already commented that the only workaround is to manually respond to an end-request event and do some manual logging.
We have some other workarounds documented here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking#http-request-in-owin-self-hosted-app

We don't have anybody on our team currently assigned to this so I can't commit to a timeline.
My understanding is that we're collaborating with a partner team to build OWIN support, but at this time we don't have any commitments from them either.

What I did learn today is that there are more workarounds that have been shared across teams.
I'm going to reach out and see what can be done to get these collected and published. 

Thank you for your patience and continued interest.
