### ISSUE TITLE
Add option EnableAuthenticationTracking to add AuthenticatedUserId to telemetries

### ISSUE THREAD

**Issue by froitag** [microsoft/ApplicationInsights-dotnet#1431]
As microsoft/ApplicationInsights-aspnetcore#442 has shown, there is a demand for an easy option to track authenticated users. There is already an option `EnableAuthenticationTrackingJavascript` which injects a JavaScript snippet that populates the `UserContext.AuthenticatedUserId` on the frontend. However, this of course only works if you have the frontend directly integrated into your application and doesn't work with pure API apps which are quite common in the era of SPAs where backend and frontend are strictly separated.

**Proposal:**
I propose introducing a new option `EnableAuthenticationTracking` which works similar to `EnableAuthenticationTrackingJavascript` and populates telemetry's `UserContext.AuthenticatedUserId` with the authenticated user's `IIdentity.Name`. Instead of relying an a frontend JavaScript snippet, an `ITelemetryInitializer` is used to set the user id on the telemetries. `EnableAuthenticationTracking` should be disabled by default as it captures personally identifiable information.

**Justification:**
The proposed approach is the same as with existing `EnableAuthenticationTrackingJavascript`.

Populating `UserContext.AuthenticatedUserId` adds the tag `ai.user.authUserId` with the corresponding user id to telemtries. In the Application Insights resource, this is used to populate property `user_AuthenticatedId` and the `Users, authenticated` metric in the metrics explorer. 

The authenticated user's `IIdentity.Name` is the perfect match for `UserContext.AuthenticatedUserId` as it is usually populated from claim `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` by default (e.g. in ASP.NET Core Identity) which is defined as the user's unique name. Furthermore, the user can easily re-map `IIdentity.Name` to a different claim if necessary, e.g. in ASP.NET Core Identity by adjusting `ClaimIdentityOptions.UserNameClaimType`.

**Comment by bdschaap** [comment]
I wanted to see if there were plans to include this feature soon.

**Comment by jmoralesv** [comment]
Hi all,
Is this issue already addressed by this class: https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/Web/Web/AuthenticatedUserIdTelemetryInitializer.cs ?

From what I can see in the `AuthenticatedUserIdTelemetryInitializer`, this looks to be the case but applies for legacy ASP.NET 4.x web apps, it doesn't work under ASP.NET Core web apps, right?

Is there any plans on addressing what @froitag mentioned in his issue at the top or a similar approach for ASP.NET Core? As far as I can see, we would need to have the Application Insights JavaScript tracking script + an `ITelemetryInitiliazer` implementation in order to store the auth user id from end to end. So far, the JS tracking script only records the auth user id in telemetry sent from JS (even when using `appInsights.setAuthenticatedUserContext(userName, null, true)`), but telemetry recorded in the back-end side in ASP.NET Core doesn't recognized that auth user id sent from JS.

Regards,
Jorge

**Comment by cijothomas** [comment]
No work has been done to make this happen in Asp.Net Core, this is an open issue.
No features are planned this year as well, so this is unlikely to be supported in near future.

This would need to be solved eventually in OpenTelemetry SDK+ApplicationInsights exporter, when they become ready.

**Comment by jmoralesv** [comment]
Hi @cijothomas,
Thanks for the heads-up, it makes sense. It looks like it won't be addressed anytime soon in Application Insights.

Is there a roadmap for the OpenTelemetry SDK? It looks like a new product or service.

**Comment by cijothomas** [comment]
> Hi @cijothomas,
> Thanks for the heads-up, it makes sense. It looks like it won't be addressed anytime soon in Application Insights.
> 
> Is there a roadmap for the OpenTelemetry SDK? It looks like a new product or service.

https://docs.microsoft.com/en-us/azure/azure-monitor/faq#opentelemetry Please check this link.
