### ISSUE TITLE
ApplicationInsightsAppender represents even debug log messages as ExceptionTelemetry

### ISSUE THREAD

**Issue by fschmied** [microsoft/ApplicationInsights-dotnet#1472]
I want to raise the question if it's a good idea that `ApplicationInsightsAppender` sends every log message that includes an exception object as `ExceptionTelemetry`, even DEBUG or INFO messages.

It seems to me that the Application Insights portal presents `Exceptions` in a way as if they were equivalent with failures or problems within an application. If this is right, then sending `ExceptionTelemetry` just because a log message references an exception object is quite misleading. For example, when we catch an exception caused by user input, we might log it on DEBUG or INFO level, then continue our work normally. We don't want Application Insights to regard this as a problem condition.

Maybe only ERROR and FATAL log messages should be logged as `ExceptionTelemetry`? Or am I misreading the meaning of `ExceptionTelemetry`?

**Comment by drauch** [comment]
We tried to convert ExceptionTelemetry items to TraceTelemetry items in a telemetry processor, however, that doesn't work because the new TraceTelemetry item does not have a proper context set and is never logged (because it has, e.g., no AppInsightsKey set in the context). Proper initialization of a telemtry item is only done by TelemetryClient.

We found a "hackaround" here https://stackoverflow.com/questions/58709519/change-telemetry-type-in-telemetry-processor but we think that's not really a solution, because the item would run through the whole pipeline again.

Our last resort is now to fork the ApplicationInisghtsAppender. Do you have a different recommendation?

Best regards,
D.R.

**Comment by fschmied** [comment]
In case anyone needs a working solution: We ended up forking and changing the `ApplicationInsightsAppender`.
