### ISSUE TITLE
Install package "Microsoft.ApplicationInsights V2.11.0" failed

### ISSUE THREAD

**Issue by Luokun2016** [microsoft/ApplicationInsights-dotnet#1480]
When I install "Microsoft.ApplicationInsights V2.11.0" using Nuget in VS2015.

Following error occures:
Failed to add reference. The package 'Microsoft.ApplicationInsights' tried to add a framework reference to 'System.Net.Http' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by Dmitry-Matveev** [comment]
@joperezr, could it be caused by the fact that AI 2.11 references System.DiagnosticSource 4.6.0 that brings in System.Memory with Net Standard targets instead of .NET 4.6?

This looks similar to other cases where System.Net.Http was not found after installation of AI package but in reality the issue was in the wrong target?

**Comment by joperezr** [comment]
> could it be caused by the fact that AI 2.11 references System.DiagnosticSource 4.6.0 that brings in System.Memory with Net Standard targets instead of .NET 4.6?

mm not exactly, basically the App Insights nuspec specifies that if the package gets restored targetting net45 or net46, then there should be a frameworkReference element added for System.Net.Http which is expected to be installed on the machine. We would need more info in order to better diagnose this. Ideally we would have a repro project (to be able to check which version of .NET the project is targeting) as well as a binlog file of the build once the problem arises. Also it would be good to know the version of the framework that is installed on the machine where we are attempting to add this framework reference, as the error kind of tells me that this project is targeting .NET 4.5 or 4.6 but has a older version installed and doesn't have the appropiate Targeting Pack.
