### ISSUE TITLE
Javascript snippet does not include Sub Resource Integrity parameters

### ISSUE THREAD

**Issue by tcarabine** [microsoft/ApplicationInsights-dotnet#1491]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1.  Add the Microsoft.ApplicationInsights.AspNetCore package to a web application
2. Follow the steps in https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-client-side-telemetry-for-web-applications to add client side telemetery
3. Run the application and inspect the injected javascript

##  Actual Behaviour
A script tag is added without SRI fields set

## Expected Behaviour
Sub Resource Integrity fields to be set on the script tag

## Version Info 
.NET Version : NetCore 2.2				
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Any
Hosting Info (IIS/Azure WebApps/ etc) : Any

**Comment by TimothyMothra** [comment]
@tcarabine, Thank you for your PR!
I'm reluctant to take this PR because our team does not own the "javascript snippet". We get updates from https://github.com/microsoft/ApplicationInsights-js and if I take your bug fix here, we'll lose it the next time we update.

@Markwolff can I transfer this issue to your repo?

**Comment by markwolff** [comment]
Hi @tcarabine we do not include any SRI in the snippet because we update the underlying file on the CDN to enable auto updating. You can welcome to include it for your own implementation, but it will likely break when we roll out updates. To get around this, you can modify the url to the CDN in the snippet to a hardcoded version, e.g. locate `ai.0.js` in the snippet and change it to `ai.1.0.20.0.js`

**Comment by TimothyMothra** [comment]
I'm closing this issue. 

if you still have questions, feel free to reopen.
