### ISSUE TITLE
Dependencies not logged when TaskCancelled Exception occurs in HttpClient.SendAsync

### ISSUE THREAD

**Issue by kvbreddy** [microsoft/ApplicationInsights-dotnet#1505]
When TaskCancelledException is generated while invoking the SendAsync on HttpClient with CancellationToken.None, then this HttpRequest is not logged as dependency. TaskCancelledException occurs mostly due to the timeout. 

## Repro Steps
1. Using the following code to send a HttpRequest:

`HttpResponseMessage httpResponseMessage = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, CancellationToken.None);
`

##  Actual Behavior
No dependency logged.

## Expected Behavior
Dependency should be logged with blank result code and duration before timeout.

**This is impacting our alerts based on dependency failures as they not being tracked now.**

## Version Info 
SDK Version : Microsoft.ApplicationInsights.AspNetCore 2.7.1
.NET Version :	4.7.1						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : Kestrel Server in a container on an Azure VM

**Comment by Dmitry-Matveev** [comment]
I checked on the latest stable version of AI .NET Core SDK (2.12) to warrant the fix for 2.13 but things actually worked out: I got Remote Dependency reported right before VS output lit up with `TaskCanceledException`.

@kvbreddy , do you host this .NET app on full .NET but in Kestrel? (Description suggests 4.7.1 as a target .NET). I hosted on .NET Core 3.0 and it may explain the difference.

Also, did you use `POST` of `GET` in `SendAsync()`? I used `GET` in the repro.

**Comment by kvbreddy** [comment]
@Dmitry-Matveev, I apologize for delayed response. My notification settings were not configured properly.

I used GET in SendAsync(). I Could simulate it locally in VS as well by using fiddler to simulate slow connections using modem speeds.

**Comment by Dmitry-Matveev** [comment]
@kvbreddy, in my repro attempt I was just causing an actual timeout between Service A and Service B by making API in Service B to fail to respond within several minutes.

```
HttpRequestMessage httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, "https://localhost:44330/weatherforecast");
HttpResponseMessage httpResponseMessage = await httpClient.SendAsync(httpRequestMessage, HttpCompletionOption.ResponseContentRead, CancellationToken.None);
return await httpResponseMessage.Content.ReadAsStringAsync();
```

Then, another API was just hanging around:
```
[HttpGet]
public IEnumerable<WeatherForecast> Get()
{
     System.Threading.Thread.Sleep(300 * 1000);
```

I'm getting Http Dependency reported after 100 seconds timeout and `System.Threading.Tasks.TaskCanceledException`.

Can you please share some code & hosting/runtime info from your local repro, so that I'm looking at what you're looking? :)
I think there is a subtle difference between our approaches - code / hosting / target runtime platform...

**Comment by kvbreddy** [comment]
@Dmitry-Matveev, here is the [repo](https://github.com/kvbreddy/testApplicationInsightsDependencyLogging/tree/master/testApplicationInsightsDependencyLogging) of the with which I could reproduce it locally. With Thread.Sleep I too was able to see that dependencies were being logged. But simulating slow speeds(Rules-> Performance->Simulate Modem Speeds) in fiddler, I was able to reproduce it(dependencies not being logged). With Thread.Sleep, I think there is no continuous transfer of data, but by simulating slow connections, there is continuous transfer of data. This might be the difference in our approaches. 


![image](https://user-images.githubusercontent.com/9054991/74076953-d68fe080-49d0-11ea-986a-3080081006f5.png)
![image](https://user-images.githubusercontent.com/9054991/74076968-f45d4580-49d0-11ea-8e14-90de4179eaf6.png)

**Comment by Dmitry-Matveev** [comment]
@kvbreddy , I was able to reproduce the issue with the solution provided and the Fiddler's modem simulation. Unfortunately, I wasn't able to debug with 2.10 version of Dependency Collector (symbols were not available on symbol server).. After updating to 2.13 version of SDK and, consequently, to 2.13 version of Dependency Collector, symbols were hooked up but the issue changed a little: now, the Dependency is reported with 30 seconds duration and success, although it's still in progress by that moment. I will take a closer look and will continue with 2.13 (that's the one we can debug ATM). Let me know if updating to 2.13+ yields the same result for you.

**Comment by kvbreddy** [comment]
Any update. @Dmitry-Matveev do you still require me to test the 2.13 version?

**Comment by Dmitry-Matveev** [comment]
@kvbreddy , sorry, I'm currently transitioning this investigation internally, new owner will help.
The current state is:
- Using repository provided by @kvbreddy , the issue is reproduced: when Fiddler imitates modem speeds, dependency telemetry for timing out HTTP `GetAsync()` is not reported in 2.10 SDK.
- Updating the same application to SDK 2.13 to debug (2.10 does not have symbols available ATM) changes behavior: such timing out dependency is collected as a successful dependency with 30 seconds duration instead.
- This seems to be the issue where SDK reacts to Diagnostics Source event from HTTP Client before the whole call is completed, so either Diagnostic Source for HTTP fires it inappropriately while call is still in progress or we react to the first event in the series of DS events from HTTP and need to reconsider our logic.

**Comment by rajkumar-rangaraj** [comment]
@kvbreddy , I continued the investigation with SDK 2.13 and see dependency is collected once we have response header. 

Collected ETW trace for both System.Net and Application Insights which helped understand an issue.

We don't wait for the entire response body to track the dependency telemetry. Even after the receiving `TaskCanceledException` we track dependencies.

![image](https://user-images.githubusercontent.com/9479006/77598945-6f66b680-6ec0-11ea-86bf-2fdab4e8cd8c.png)

Could you please check.
