### ISSUE TITLE
404 errors are all grouped under the same route making it hard to look through

### ISSUE THREAD

**Issue by xt0rted** [microsoft/ApplicationInsights-dotnet#1555]
I've just moved my site over to asp.net core 2.0 using the `UseStatusCodePagesWithReExecute` middleware. Prior to this migration I was only using the Site Extension (the site was owin & nancy so I couldn't really use the sdk in the application) and when a 404 error came through the portal would show the actual url path. Now I'm seeing all 404 errors grouped under the same basic name of `GET Home/Error [errorType]`.

Is there a way to report/show the requested path instead of the error page that gets shown? Right now [this is what I'm seeing for the last 24 hours](https://user-images.githubusercontent.com/831974/34488795-cb338eb0-efa7-11e7-988e-b8699a36a2db.png). There's about 8 different paths that produced these 18 entries but you don't know that without going through each entry.

Another thing I'm noticing is there's no info such as referrer or browser info. Should that information be included in the error details? It seems really useful in helping to track down where the issue may have come from. A good example of this is older versions of iOS Safari don't seem to handle spaces in file downloads and as a result a 404 is returned with a partial path such as `/downloads/monthly` which could be for any file that starts with `monthly` and span various pages on the site.

## Version Info 
**SDK Version:** 2.2.0 Beta 3
**.NET Version:** .net core 2.0
**How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :** NuGet & Site Extension
**OS:** Server 2016
**Hosting Info (IIS/Azure WebApps/ etc):** Azure WebApps

**Comment by EdiWang** [comment]
Any update on this? It's April 2020 now, I am still being frustrated by this issue every single day.

**Comment by cijothomas** [comment]
@EdiWang Can you confirm if your url is populated correctly for 404 occurences? If yes, this issue is not required to be fixed at SDK level, but at UI - thoughts?

**Comment by EdiWang** [comment]
@cijothomas the problem is after using `app.UseStatusCodePagesWithReExecute("/error", "?statusCode={0}");` the application insights data are grouped under "Error/Error" or "Home/Error" in @xt0rted 's case. Although we can click into each single one of them to see the actual request URL, it makes us extremely hard to check the 404 URLs on the application insights Failures page.

I don't know if this issue is in ASP.NET Core runtime or in Application Insight. 

The reason many people use `app.UseStatusCodePagesWithReExecute("/error", "?statusCode={0}");` is to display a friendly custom error page but preserve the URL. Without it, the app will just return error code response without body.
