### ISSUE TITLE
A way of telling if telemetry data was received

### ISSUE THREAD

**Issue by YaronK** [Microsoft/ApplicationInsights-dotnet#164]
## In a nutshell: ##
I need a way of telling if the telemetry data I sent was successfully received.
Ideally having the API provide me this information, or alternatively a fair way of knowing if the telemetry server is up.

## Details: ##
I have been using the C# API and am now additionally embedding the JS (angular) API.
The application’s backend is written in C# and the frontend in JS (management web console).

In some cases, the backend cannot reach the web whereas the frontend can.
By default, I want to send telemetry from the backend. 
When not possible, I want to send from the frontend.
Also, I’d rather not send duplicates (from either the frontend and the backend, or from several frontends).

Ideally I’d have a way of telling if the attempts to send telemetry data were successful.
But it seems both the APIs are async and there’s no way to tell if the data was sent successfully after sending it.
**Could you recommend a way to tell whether the telemetry data was in fact sent?**

Another option is to check Internet connectivity, though this is less than ideal, or to check if the telemetry server is reachable. 
Since the telemetry server’s url provides a restful API, I can’t ping it or send an HTTP GET request to it.
**How would you suggest to check the telemetry server’s availability if the API doesn’t support this need?
Do you use any such mechanism?**

**Comment by SergeyKanzhelev** [comment]
Application Insights SDK has couple telemetry channels out of the box - InMemory channel and Server Telemetry Channel. Read here: http://apmtips.com/blog/2015/09/03/more-telemetry-channels/

Both of them are async and here is what @abaranch wrote about the way to detect whether item was sent or not. TL;DR;- it's very hard to do:


> We do not have an easy way to do this. 
>Each telemetry item is added to a transmission package, this transmission package can be either sent successfully as one whole thing or failed to be sent. 
>But if we failed to send transmission out we store it on disk and retry later. So we will report an error only if storage is full and transmission is dropped.

>All failed transitions between senders, buffers and storage we report as warnings that we post as ETW events. There are no subscribers to warnings by default.
>To subscribe to that you can use perfview.
>Please read this: http://apmtips.com/blog/2015/11/07/application-insights-self-diagnostic/
>Verbose level also includes all transitions including what telemetry types were added to a single transmission.

So @Yonisha end up implementing synchronous custom implementation of telemetry channel. This [interface `ITelemetryChannel`](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/271edd5fd8b9c7d84a9bd72448ec14f9b2145259/src/Core/Managed/Shared/Channel/ITelemetryChannel.cs#L13)


W.r.t. checking an endpoint for availability - Easiest you can do is to check that you have internet connectivity. Application Insights endpoint availability is quite good. If you want to check endpoint availiability - there is a new endpoint `/v2/validate`. You can `POST` simple event and get success/failure response in return. 

Here is how you get JSON to send:
```
TraceTelemetry telemetry = new TraceTelemetry("ping");
telemetry.Context.InstrumentationKey = "Foo";
telemetry.Timestamp = DateTime.Now;

var content = JsonSerializer.Serialize(new List<ITelemetry>() { telemetry }, true);
```
Here is how you serialize and send `POST`:

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/4dd948ef9c4ca26ecfd6e76adf3e5af0f59d7bcf/src/Core/Managed/Shared/Channel/Transmission.cs

**Comment by YaronK** [comment]
Thank you, Sergey.

Regarding **checking an endpoint for availability**:
Can I rely on the 'validate' endpoint? Will it exist 'forever'?
Also, there isn't any significance to the telemetry's content ("ping"), right?
Implementing this, I set the web request's ContentType to "application/x-json-stream" and added a Content-Encoding with the value of JsonSerializer.CompressionType.

**Comment by SergeyKanzhelev** [comment]
sorry for long delay - having a cold now. We plan to have this validate endpoint for some time. You can also send telemetry to the separate instrumentation key with the same result =).

BTW, here is an example on how to use this endpoint: http://apmtips.com/blog/2016/02/11/validate-event-json/

**Comment by daniel-kun** [comment]
I am running in a smiliar problem. We are right before releasing the first version of our software that uses Application Insights to collect usage stats - it's a classic Win32 / .NET hybrid Desktop App (which is quite some trouble in itself, but that is another story). We are using the Application Insights Core API for this.

We wrote a Console application that sends the usage statistics, however, we noticed that only a fraction of it was delivered. We learned that Sampling was kicking in a way that we did not anticipated, and set the sampling rate to 0. All this took quite a bit of experimentation and a lot of metrics were sent. (We are *only* using Metric Telemetry at this time.)

At this time we have to keep the Console app running for the InMemory telemtry channel runner send the "huge" amount of cached metrics that accumulated in the experiments and haven't been send. This is quite frustrating since we don't know how much has been sent and how much is there left in the queue, so we are just sitting there and waiting, refreshing the Portal from time to time to see whether the latest metrics have been sent.

So we would love to either a) clear the internal cache and discard the metrics or b) have a tiny bit of an idea of whether there are still metrics in the queue that have to be sent. Besides, I was once told that the telemetry is cached offline somewhere and will be sent the next time the App runs. Where exactly is it stored in the file system?

**Comment by abaranch** [comment]
@daniel-kun InMemory channel does not have local cache on disk. It buffers telemetry for 30 seconds and than sends it out. It also does not have retry logic. It has sync Flush method if you want to force data to be sent immediately. Read this: http://apmtips.com/blog/2015/09/03/more-telemetry-channels/
