### ISSUE TITLE
Custom metric ingestion slow

### ISSUE THREAD

**Issue by mrdotmoon** [microsoft/ApplicationInsights-dotnet#1673]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
We are writing the custom metrics to application insight in asp.net core.  And we have called Flush() every time. But the custom metric ingestion is slow, and it always need to take 2 - 3 minutes to show in the logs. Our service's auto scale is based on these custom metrics and 3 minutes delay will cause some issue. Is there any way to make ingestion faster?

## Version Info 
SDK Version : Microsoft.ApplicationInsights.AspNetCore 2.12.1
.NET Version : .net core 3.0					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Linux
Hosting Info (IIS/Azure WebApps/ etc) : AKS

**Comment by Dmitry-Matveev** [comment]
One of the faster ways is to use Metric store, not the Logs store for auto scale. If you are already configuring scaling on top of metric store, and not with AI Analytics query, then you're on the right/fast pipeline.

Is there a way you can set some proactive value for scale alert, so it will react sooner even with 2-3 min delay?

Alternatively, you can go all the way into scaling based on predictive Analytics query and have your service scale if projected/extrapolated trend of the resource you're tracking is about to hit the limit, instead of scaling after it hits the limit, e.g. with something like [slope analysis and trend prediction in Analytics](https://docs.microsoft.com/en-us/azure/kusto/query/series-fit-linefunction).

**Comment by mrdotmoon** [comment]
I am using the Azure Kubernetes Service, which's auto scale is using Application insight.
https://github.com/Azure/azure-k8s-metrics-adapter

Looks like they are using api https://api.applicationinsights.io/v1/apps/<appid>/metrics/customMetrics, is it the faster way you were referred to?

**Comment by Dmitry-Matveev** [comment]
I think that [this API](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/rest-api-walkthrough#retrieve-metric-values-multi-dimensional-api) retrieves metrics from the metrics storage. It is different from `api.applicationinsights.io` that would query metrics from the log storage.

Default Azure Portal experiences such as metrics charts or alerts should actually query metrics storage as per my understanding. If the experience you are working with does not go through metrics store, you can still try to apply predictive analytics I described earlier to work around the issue and scale preemptively instead.

**Comment by cijothomas** [comment]
Are you using TrackMetric() or GetMetric().Track() to write custom metrics? The latter does in-proc aggregation and telemetry is only sent once every minute. The channel also has a send policy of once every 30 secs, or 500 items in buffer, Together these may add 1-2 minutes delay at the client side itself.
