### ISSUE TITLE
Heartbeat not working for WorkerService

### ISSUE THREAD

**Issue by danspam** [microsoft/ApplicationInsights-dotnet#1689]
The heartbeat relies on IHeartbeatPropertyManager being available on `TelemetryModules.Instance.Modules`, however this collection is empty when you add AI using `services.AddApplicationInsightsTelemetryWorkerService()`. 

You can make it work by adding, for example, `var _ = TelemetryConfiguration.Active;`, which initialises `TelemetryConfigurationFactory` adds the `DiagnosticsTelemetryModule` to the modules collection. However, `TelemetryConfiguration.Active` is obsolete and this does not seem like the correct thing to do. You would expect it to just work?

## Repro Steps
1.  Add application insights to worker service using `services.AddApplicationInsightsTelemetryWorkerService()`
2. Deploy service to VM
3.  Look for "HeartbeatState" in customMetrics

##  Actual Behavior

No HeartbeatState appears in customMetrics

## Expected Behavior

HeartbeatState appear in customMeterics

## Version Info 
SDK Version : 2.12.1
.NET Version : Core 3.1	
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : Windows VM Service

**Comment by TimothyMothra** [comment]
@cijothomas please review.

**Comment by cijothomas** [comment]
This issue about heartbeat is not solved fully.
As a temporary workaround for WorkerServices, you can manually add `DiagnosticsTelemetryModule` to DI and configure it's heartbeat interval.

```
services.TryAddSingleton<ITelemetryModule, DiagnosticsTelemetryModule>();
                    services.ConfigureTelemetryModule<DiagnosticsTelemetryModule>((mod,opt) => mod.HeartbeatInterval = TimeSpan.FromSeconds(30));
                    services.AddApplicationInsightsTelemetryWorkerService();
```

@danspam Please use the above snippet to add/config heartbeat module. We don't recommend touching tc.active. (Due to back-compatibility reason, our asp.net core sdk is doing it, but worker service is new sdk, and its not touching .active or any other static singletons)
