### ISSUE TITLE
Should the Appsettings.json not-provider specific LogLevel apply to the ApplicationInsights Logging Provider?

### ISSUE THREAD

**Issue by aluong** [microsoft/ApplicationInsights-dotnet#1756]
**Describe your environment.**
 Running a .Net Core Console App and using this extension method to add ApplicationInsights logging:
```
services.AddApplicationInsightsTelemetryWorkerService();
```
* SDK version: 2.13.1
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): .NetCore 3.1
* Hosting Info (IIS/Azure WebApps/etc): Console App
* Platform and OS version: OSX 

**What are you trying to achieve?**
What did you expect to see?

When I do not specify the `ApplicationInsights` provider section in my `appsettings.json`, none of my `Information` level logs are being sent to Application Insights. 

**No** Information level logs are being sent to Application Insights
```
"Logging": {
    "LogLevel": {
      "Default": "Information"
    }
```

Information level logs **are** being sent to Application Insights
```
"Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Information"
      }
    }
  }
```

However, [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configuration) seems to imply that the provider section is purely overriding the log level. Shouldn't all providers (ex: ApplicationInsights) inherit the base level if that is the case?
```
If levels are specified in Logging.{providername}.LogLevel, they override anything set in Logging.LogLevel.
```

**Additional context.**

Both of these docs seem to imply adding a specific Provider section in the Logging setting should just override. Consequently, I would assume that setting a generic / base LogLevel should be inherited by all providers.

- https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#create-filter-rules-in-configuration-with-appsettingsjson 
- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configuration

**Comment by cijothomas** [comment]
`ApplicationInsightsLoggingProvider` is configured to collect Warning or above by default when you enable application insights using `services.AddApplicationInsightsTelemetryWorkerService();`
https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#ilogger-logs

It won't inherit the base, because, its is configured to collect Warning or above only. This is by design, as ApplicationInsights is a paid product, and we want customers to make explicit choice if they want to sent more logs to ApplicationInsights.

**Comment by javedali-dev** [comment]
I want to enable app insight to send all the logs not only the log that is higher than the warning. How can I enable it in asp.net core application?

**Comment by jamesmanning** [comment]
@javedali-dev I realize this is well over a year old, but you just need to explicitly set the default log level for the ApplicationInsights logging provider under the Logging node of your appsettings. This is very easy to get wrong because there's *also* typically an "ApplicationInsights" node within the json that's a peer of Logging which is where you can configure the instrumentation key / connection string, but for the purposes of changing the default log level, you need the "ApplicationInsights" node that's a child of the Logging node (this means it's the configuration that will apply to the "ApplicationInsights" logging provider), then provide a LogLevel node under there so the default config of logging at Warning can be overridden so the default can be Information (or Debug, Trace, whatever based on your needs)

https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core?tabs=netcorenew%2Cnetcore6#how-do-i-customize-ilogger-logs-collection

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Information"
      }
    }
  },
  "ApplicationInsights": {
    "ConnectionString": "InstrumentationKey=00000000-0000-0000-0000-000000000000"
  }
}
```
