### ISSUE TITLE
AI.config file is being read for loading TelemetryConfig in .net core

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1795]
.NET Core/ASP.Net Core is not supposed to use AI.config file for configuration. The `platform implementation` class was supposed to return null for AI.Config contents. But this got broken when NETSTANDARD20 target was added.

https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Platform/PlatformImplementation.cs#L1

This is a bug, can cause issues if an AI.Config file is present in application bin folder. (Maybe an old leftover with different ikey etc.)

Fix would be to make sure we read AI.Config only in .NET Framework

**Comment by TimothyMothra** [comment]
adding to this..
- using the `NETSTANDARD` here will fix the compilation for all versions of net standard (instead of version-specific)
https://github.com/microsoft/ApplicationInsights-dotnet/blob/7e9f17d3fa2181dc927f7448b34c2289cfedee15/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Platform/PlatformImplementation.cs#L1-L3

- we should review if we have proper test coverage around this.
