### ISSUE TITLE
SnapshotCollector non-Windows OS support

### ISSUE THREAD

**Issue by scp-mb** [microsoft/ApplicationInsights-dotnet#1901]
Following on from the repo consolidation this issue was still open without resolution on one of the now archived repositories:

https://github.com/microsoft/ApplicationInsights-Home/issues/188

Has there been any updates or timescale on when snapshot collection will work on non-windows environments? We're looking at moving our infrastructure to containers, but the snapshot collector throws an exception on startup if the container isn't a Windows container.

**Comment by TimothyMothra** [comment]
@pharring can you comment?

**Comment by priyanr** [comment]
As per @pharring 2019 aug update they have it somewhat working. I wonder why there is not much requests for this. Hopes this will soon happen.

**Comment by wolszakp** [comment]
Any updates for this?

**Comment by pharring** [comment]
Sorry, no. The team has been busy with other things. 

On a related topic, I heard some good news the other day: It is now possible to to "cross OS" debugging of memory dumps using Concord (the debug engine at the heart of Visual Studio and VS Code). What that means is that our analysis service (which runs on Service Fabric on Windows) will be able to analyze dumps created on Linux. This means we should be able to do all our analysis on Windows VMs -- rather than spinning up Linux VMs/containers just to run the analyzer (which was what I was talking about here: https://github.com/microsoft/ApplicationInsights-Home/issues/188#issuecomment-519110822)

**Comment by wolszakp** [comment]
This is not the best news. However thanks @pharring for info.

**Comment by pharring** [comment]
Please move the discussion to the [SnapshotCollector](https://github.com/microsoft/ApplicationInsights-SnapshotCollector/issues/2) repo
