### ISSUE TITLE
How can I filter ALL telemetry within request scope?

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet#192]
Using telemetry processor I can filter my requests according to certain attributes, for example query string parameters or request path, which is really useful. However if I don't care about this path, what I really would like to do is ignore all telemetry for this request path, not just requests.
I would be useful if I could get to an instance of RequestTelemetry from ITelemetry.Context.OperationContext. Then in my telemetry processor I could do something like this:
```
if (IsIgnoredPath(item.Context.Operation.ParentRequest.Uri))
{
 return;
}
else
{
 this.Next.Process(item);
}
```
Is there any way I can do it today?

**Comment by abaranch** [comment]
I guess this question is related to Web SDK rather than Core (since in Core depending on how you create telemetry item you would have your own method of sharing it with the rest of your code)
For Web SDK
1. If you are interested in a Path. That would ne your HttpContext.Current.Request.Path that you are interested in 
2. If there are some properties in RequestTelemetry you should use HttpContext extension method: System.Web.HttpContextExtension.GetRequestTelemetry
