### ISSUE TITLE
Add an option to disable adding "Correlation-Context" but keep "Request-Id" or W3C http header

### ISSUE THREAD

**Issue by uuggene** [microsoft/ApplicationInsights-dotnet#1951]
**Is your feature request related to a problem?**
We keep in Activity.Baggage a lot of data and we want to pass them as custom dimensions to AppInsights.
But we don't want to pass this data in http headers as part of dependency http requests. (As a result we get 400 Bad Request Too long http headers)
I'd like to keep the calls chain between servers (requests and dependencies), but don't send what we have in Activity.Baggage.

**Describe the solution you'd like.**
I'd like to see an option in DependencyTrackingTelemetryModule. Something like:
 'SetComponentCorrelationContextHttpHeaders': True/False.
There's existing setting SetComponentCorrelationHttpHeaders, which disables adding all correlation http headers.

**Describe alternatives you've considered.**
As I can see there's a workaround: just add empty or custom "Correlation-Context" http header.

**Comment by cijothomas** [comment]
Activity.Baggage is intended to carry data to downstream. Its by design and is not a feature of Application Insights.
(https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#baggage)

Use tags instead : https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#tags
