### ISSUE TITLE
Auto correlation of telemetry events

### ISSUE THREAD

**Issue by rajatshetty** [microsoft/ApplicationInsights-dotnet#1964]
We have our own SDKs built on top of application insights, earlier we have talked on correlation and distributed tracing, we were doing some custom implementation on handling a cross correlation id which is similar to operationId.

We did some progress on this for .net core application, we are finding it difficult to do the same for .net application.

In .net core we used Activity and System.Diagnostics intercepted the Http calls to attach the cross correlationid the way it is done in Application insights SDK, but when it comes to .net application (For ex: ASP.net webapi)  we are facing issues in retaining the Activity baggage values, when the Http request completes the Activity becomes null.

I wanted to understand if there is any limitation specifically for .net applications (from 4.5 to 4.6.2) or in the dependent libraries like Diagnostics

**Comment by cijothomas** [comment]
I am not sure if this is a question for this repo. This repo is just a consumer of the DiagnosticSource events emitted by the actual libraries/frameworks. So if you find an issue with .NET or Asp.NET WebApi 'losing' baggage and Activity becoming null - its an issue to be opened with the corresponding repo.

An if the issue is real bug - then application insights (in this repo) is also likely affected. We are interested in it, but cannot investigate it. If you share a minimal repo, then we can try to investigate, but its best opened in the corresponding repo.
