### ISSUE TITLE
Adaptive Sampling - average

### ISSUE THREAD

**Issue by darthkurak** [microsoft/ApplicationInsights-dotnet#1980]
Hello everyone.
I have question about adaptive sampling and then logs which i see in App Insights.
For example - i have dependency to Azure Service Bus, and with that - many logs about Send operation, sampled.
I see ItemCount = 100, and then Duration time.
The question is - that Duration time is an average of this 100 sampled Sends duration time for particular topic, or it is some arbitrary chosen  duration time of single sample of this one hundred? 
I am asking, because i am seeing huge difference between what i got in App Insights where 99th over 100 sampled logs for specific topic is around 6s, but in prometheus, where i track histogram metrics, the same topic over same time, has 0,02 s.

**Comment by cijothomas** [comment]
> The question is - that Duration time is an average of this 100 sampled Sends duration time for particular topic, or it is some arbitrary chosen duration time of single sample of this one hundred?

The later is correct.

**Comment by darthkurak** [comment]
Wow. So, actual, you cant rely on reported times when you have sampled logs? Why this is not averaged? How this single duration value is chosen from sampled logs?

**Comment by darthkurak** [comment]
And if so, how all performance tab work with sampled data?

**Comment by cijothomas** [comment]
If one wants to have truly accurate telemetry - then sampling defeats the purpose, as sampling cannot ensure any info about the items which are dropped. The retained item is represented accurately - its response time, and all other properties are represented as such. Averaging or doing any calculation causes losing an actual telemetry to investigate. If 10 dependency telemetry was produced and only 1 of them was retained by sampling - that item will have all its fields accurate and true. Since its "representing" 10 items, `itemCount` will be set to 10. (like a weightage). This itemCount is used by UI experiences to compensate for sampling. Of course accuracy is lost. Nothing can be deducted accurately about the 9 items which were sampled out  - nothing can be truly known about the dropped items other than knowing they were of DependencyTelemetry. Its response code, http target, duration - nothing can be known.

Despite sampling, the StandardMetrics are always accurate as they are extracted pre-sampling. 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics#pre-aggregated-metrics
