### ISSUE TITLE
SnapshotCollector Uploader crashes on IIS shutdown

### ISSUE THREAD

**Issue by kltye** [microsoft/ApplicationInsights-dotnet#2097]
Using SnapshotCollector with .NET Core 3.1 hosted in IIS. Upon shutting down the app pool (whether using _iisreset_ or app_offline.htm), it looks like the uploader crashes. This is logged in the event log:

Application: w3wp.exe
CoreCLR Version: 4.700.20.26901
.NET Core Version: 3.1.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more errors occurred. (The semaphore has been disposed.)
 ---> System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at Microsoft.ApplicationInsights.SnapshotCollector.Pipeline.ProducerConsumerQueue`1.Produce(T workItem)
   at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.EnqueueRequest(Request request)
   at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.Shutdown()
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.ApplicationInsights.SnapshotCollector.ApplicationLifetimeManager.Stop()
   at Microsoft.ApplicationInsights.SnapshotCollector.AssemblyLoadContextLifetimeManager.OnUnloading(Object sender)
   at System.Runtime.Loader.AssemblyLoadContext.RaiseUnloadEvent()
   at System.Runtime.Loader.AssemblyLoadContext.OnProcessExit()
   at System.AppContext.OnProcessExit()

This becomes an issue because Windows Error Reporting kicks in, but seems to hold on to the w3wp process, which prevents us from doing a successful automated deployment to the server; someone has to kill werfault.exe in order for w3wp to fully die, and release any file handles it has.

Any ideas what I might be doing wrong? My startup.cs is pretty simple for this:

```
services.AddSnapshotCollector((config) =>
            {
                if (!string.IsNullOrEmpty(_configuration.GetValue<string>("ProxyServer")))
                    config.UploaderProxy = $"{_configuration.GetValue<string>("ProxyServer")}:{_configuration.GetValue<string>("ProxyPort")}";
            });
```

**Comment by pharring** [comment]
Thanks for the bug report. The ObjectDisposedException is something I knew about, but I didn't know it caused problems with deployment. Sorry about that.

Unfortunately, I can't think of a workaround at the moment. I'll try to get a fix into the next release of Snapshot Collector.

**Comment by pharring** [comment]
A fix has been added to [1.4.0-pre-010.2302](https://www.nuget.org/packages/Microsoft.ApplicationInsights.SnapshotCollector/1.4.0-pre-2010.2302)

**Comment by kltye** [comment]
> A fix has been added to [1.4.0-pre-010.2302](https://www.nuget.org/packages/Microsoft.ApplicationInsights.SnapshotCollector/1.4.0-pre-2010.2302)

(Preliminary) testing shows that this fixes my issue. Thanks very much for your prompt response! I think it's safe for me to close this ticket out.

**Comment by tkp1n** [comment]
@pharring Is there already a released (non-pre) version with this fix included?

**Comment by pharring** [comment]
Not yet.
Is that a blocker for you?
Release notes are here: https://docs.microsoft.com/azure/azure-monitor/app/snapshot-collector-release-notes

**Comment by tkp1n** [comment]
Not really, but we are currently receiving alerts for the abovementioned exceptions during recycles and re-deployments of our services...

A backport of the fix to a 1.3.x release would, therefore, be greatly appreciated. Unless the 1.4 release is coming soon, of course.

I'd contribute the backport myself, but I couldn't find the relevant source code here (assuming its closed-source?).

**Comment by pharring** [comment]
@tkp1n 1.3.7.5 has been released with the fix backported. This is the only change from 1.3.7.4

**Comment by tkp1n** [comment]
@pharring What a service, thank you!

**Comment by ascholz81** [comment]
This issue is currently happening for me.  Do you have any other notes or help on it? I've even gone as far as removing the snapshot collector reference from my project.

**Comment by chassq** [comment]
We are currently seeing this error. Looks related?

<Event> 
<System>
<Provider Name=".NET Runtime"/>
<EventID>1026</EventID>
<Level>1</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2021-04-05T15:47:20Z"/>
<EventRecordID>277402015</EventRecordID>
<Channel>Application</Channel>
<Computer>RD0003FF2BD0FF</Computer>
<Security/>
</System>
<EventData>
<Data>Application: w3wp.exe CoreCLR Version: 5.0.421.11614 .NET Version: 5.0.4 Description: The process was terminated due to an unhandled exception. Exception Info: System.AggregateException: One or more errors occurred. (The semaphore has been disposed.) ---> System.ObjectDisposedException: The semaphore has been disposed. at System.Threading.SemaphoreSlim.CheckDispose() at System.Threading.SemaphoreSlim.Release(Int32 releaseCount) at System.Threading.SemaphoreSlim.Release() at Microsoft.ApplicationInsights.SnapshotCollector.Pipeline.ProducerConsumerQueue`1.Produce(T workItem) at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.EnqueueRequest(Request request) at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.Shutdown() at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj) at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback() at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) --- End of inner exception stack trace --- at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException) at System.Threading.CancellationTokenSource.Cancel() at Microsoft.ApplicationInsights.SnapshotCollector.ApplicationLifetimeManager.Stop() at Microsoft.ApplicationInsights.SnapshotCollector.AssemblyLoadContextLifetimeManager.OnUnloading(Object sender) at System.Runtime.Loader.AssemblyLoadContext.OnProcessExit() at System.AppContext.OnProcessExit() </Data>
</EventData>
</Event>
