### ISSUE TITLE
Version 3.0 API change proposal

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet#214]
# Version 3.0 API change proposal
## TelemetryProcessors

**Issues:**
- Very complex API. We have 1 interface and 3 classes for one concept (ITelemetryProcessor, TelemetryProcessor, TelemetryChain, TelemetryChainBuilder)
- Interface is same as ITelemetryInitialiser which is confusing. And we assume that constructor accepts next ITelemetryProcessor but we do not force it on API level
- If some number of processors are added in configuration file programmatically we can add processors only in the end of the chain.
- We cannot easily restructure the chain. When chain is rebuilt (e.g. if sampling or some other filter is added in code) all processors are recreated. It causes problem in Metrics Stream since module there keeps a reference on the processor.
- If TelemetryProcessor is ITelemetryModule Intilialize will be called only for processors created from configuration file but will not be called on rebuild.

**Proposal:**

Have only one interface and one class where all restrictions are forced:

```
public interface ITelemetryProcessor
{
    void SetNext(ITelemetryProcessor next);
    void Process(ITelemetry item);
}
```

That also solves the problem of rebuilding the chain dynamically.
## TelemetryModules

**Issues:**
- Concept is not fully exposed to customers but we actively use it internally (interface is public but collection of modules is hidden)
- TelemetryModules are global objects; they are data providers that do not belong to a single configuration. But since now modules publish telemetry they need some configuration so we chose TelemetryConfiguration.Active and use it to initialize module

**Proposal:**
- Introduce [GlobalConfiguration.Instance](https://github.com/abaranch/ApplicationInsights-dotnet/blob/c432f9359b72c3ff01f8f559933ae51ab4b13274/src/Core/Managed/Shared/Extensibility/TelemetryConfiguration.cs#L36) that would contain global configuration like modules
- TelemetryModule is a provider of data. It does not track anything. TelemetryConfiguration [can subscribe](https://github.com/abaranch/ApplicationInsights-dotnet/blob/c432f9359b72c3ff01f8f559933ae51ab4b13274/src/Core/Managed/Shared/Extensibility/TelemetryConfiguration.cs#L113) to any TelemetryModule to get items.

```
public interface ITelemetryModule: IObservable<ITelemetry>
{        
}
```
- Currently ITelemetryModule interface is also used when you need to get configuration in your object and that can be TelemetryInitializer, TelemetryChannel or any other object (TelemetryProcessor also can be ITelemetryModule but we do not call Initialize after rebuild which may be considered a bug). Proposal is to introduce (or rather put back since we had it once) [ISupportConfiguration](https://github.com/abaranch/ApplicationInsights-dotnet/blob/c432f9359b72c3ff01f8f559933ae51ab4b13274/src/Core/Managed/Shared/Extensibility/ITelemetryModule.cs#L13) interface. Though we would use it only for instance level objects like TelemetryInitializers and global objects like modules would not be able to use it.
## TelemetryChannel

**Issues:**
- We create separate channel for each configuration which is a waist of resources. Note that when telemetry item reaches the channel it has iKey so channel does not need a separate iKey. Also channel reads all items from disk. 
- We have wrapper object to add channel as the last telemetry processor.
- It is ITelemetryModule just because we want to initialize it after all properties are set.

**Proposal:**
- Put default channel in GlobalConfiguration. Allow adding more channels in the GlobalConfiguration programmatically (in case if we need channel with a different endpoint)
- Make channel ITelemetryProcessor.
## TelemetryConfigurationFactory

**Issues:**
- Configuration reading is super complicated because it is a mix of what to read and how to initialize it + special cases for modules and TelemetryProcessors
- TelemetryConfigurationFactory builds TelemetryConfiguration directly so if we want to add some other elements in configuration file we need special cases in parsing logic. 

**Proposal:**
- TelemetryConfigurationFactory should construct [data object](https://github.com/abaranch/ApplicationInsights-dotnet/blob/c432f9359b72c3ff01f8f559933ae51ab4b13274/src/Core/Managed/Net40/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L23) that matches configuration file structure. After that this object is used for constructing TelemetryConfiguration instance and updating global configuration objects like modules.

**Comment by tomasr** [comment]
Regarding ITelemetryProcessor, what are the threading implications of the proposed model? Could SetNext() be called while a call to Process() is in progress? Not entirely a fan of the SetNext() thing (wonder if really you should have a factory interface that is plugged in, and asked to create an ITelemetryProcessor within a chain).

Regarding the change proposed to TelemetryModule, not quite sure I understand the idea here, but seems like one core concept is decoupling the module from the TelemetryClient instance (and thus the configuration) and just have it produce an observable stream of telemetry events that the core routes to the TelemetryClient?

Another issue with configuration that doesn't seem would be addressed is the need to support multiple alternative configurations within a single process. Specifically, consider cases where you need to support multiple technologies within a single process that possibly require different configuration (such as a different set of modules).

**Comment by tokaplan** [comment]
First off, I think these are awesome changes that are long overdue and will make things infinitely easier for everyone.

Allow me to approach this from a somewhat different perspective just for the sake of organizing my thoughts clearly. This will no doubt have a lot of intersections with what you have already mentioned, but I believe will address the problem a bit more broadly. This is our chance to introduce breaking changes based on all the experience and feedback we've accumulated so far, so let's make it count.

Let's talk about the following key extension points in our pipeline (listed in the order of invocation):
- _Telemetry modules_ (i.e. you can plug in your own code that will become a telemetry item source - run in the background and generate telemetry items independently of the application)

- _Telemetry initializers_ (i.e. you can plug in your own code to enrich telemetry items that pass through the pipeline with custom data)
- _Telemetry processors_ (i.e. you can plug in your own code to filter out telemetry items that pass through the pipeline so that the ones that you don't like won't get sent out)
 
 **Telemetry modules**
 
 You have pointed out the main problem with Telemetry modules very clearly - they are indeed designed to be configuration-agnostic and global at the application level, which is not currently fully implemented. Answering @tomasr's question, I think what you're saying is that a module can not possibly Track() anything since that suggests using an instance of TelemetryConfiguration - and that's precisely what we're trying to avoid. However, I will suggest to you that introducing a new channel of delivering telemetry items to the pipeline by allowing TelemetryConfiguration to subscribe to a module's output is a bit too complicated.

 Instead, consider the following. 

 As soon as we remove the TelemetryConfiguration parameter from module's Initialize method and make the class an observable, Telemetry module becomes

```
public interface ITelemetryModule : IObservable<ITelemetry>
{	
}
	
public class SomeTelemetryModule : ITelemetryModule
{
    public IDisposable Subscribe(IObserver<ITelemetry> telemetryConfiguration)
    {
        this.telemetryConfiguration = telemetryConfiguration;
    }

    public void TrackSomeTelemetry()
    {
       this.telemetryConfiguration.OnNext(requestTelemetry)
    }
}
```
	  
  Let's not notice that we can get rid of ITelemetryModule and use IObservable<ITelemetry> instead; but what if we don't like observables and choose against introducing subscription-based design? Easy:

  ```
public class SomeTelemetryModule  // no interface...
{
    public void TrackSomeTelemetry()
    {
        TelemetryConfiguration.Active.TrackRequest(requestTelemetry);
    }
}
```
    
  There's no subscription mechanism, the customer doesn't have to figure out how to subscribe; it's all right there - and exactly the way it's done for regular Track()ing. A module is just a piece of customer's code that uses SDK through whichever TelemetryConfiguration it chooses. There's nothing under the hood.
 
  At this point we're left with no interface and no extension point. A module is just a class that uses TelemetryConfiguration to Track() stuff; its singleton is being instantiated by SDK, but is that really a good enough reason to have a notion of TelemetryModule publicly exposed? Should we really make the customer understand the subscription-based mechanism that connects TelemetryConfiguration with TelemetryModule, and be aware of TelemetryModule at all?
  
  Let's simply let the customer create his/her own TelemetryConfiguration and Track() whatever is necessary for the application. If they need a class for a specific background tracking task, they can certainly instantiate it themselves.
  
  So my proposal is to drop the publicly available extension point called TelemetryModule. It's less code, and I simply don't see a good use case for it.
  
Of course, this leaves us with an issue of having our own internal modules. Those are quite useful since SDK needs to run its own code to provide important functionality on top of the passive Track() that the application can do on its own. Clearly, we need to keep those modules intact, along with the configurability. 

We'll inevitably face the issue of having to Track() things from those modules with no configuration present, and that is where we need customer's help - he or she will have to specify which TelemetryConfiguration to use for sending the data from the (now internal) modules. Sounds very much like TelemetryConfiguration.Active, doesn't it, but we can certainly make that configuration clearer. Ultimately, our own internal modules are also pieces of code that are independent of SDK; all they need is customer's input regarding how to track their output. We can even introduce an SDK-agnostic callback for the customer to track things him/herself... 

Per-internal-module configuration is also possible if deemed useful.

To illustrate my point, consider the amount of code required to support perf collection through design that is proposed above vs through what I suggest. Let's say, a customer is implementing a feature called PerformanceCollection, in which he or she is Track()ing machine's performance counters every 5 seconds. Assuming the customer is aware of the basics of SDK (knows how to call TelemetryClient.Track***()).

With the built-in support for TelemetryModule extension point (+ subscription mechanism):
1. Read up on what TelemetryModules are and how they interact with TelemetryConfiguration through subscriptions (ReactiveExtensions? Observers? Subscribe()? OnNext()?).
2. Implement ITelemetryModule.
3. Write the code that collects perf counters and writes them to the collection of observeables that have been passed to Subscribe().
4. Create a TelemetryConfiguration (unless it's Active), figure out which TelemetryConfiguration must be subscribed to that particular module and subscribe it. Is TelemetryConfiguration.Active already subscribed if the module is in ApplicationInsights.config? What if the module is created in code?

Without the built-in support of TelemetryModules:
1. Create a TelemetryConfiguration (unless it's Active).
2. Write the code that collects perf counters and Track()s them.

In my opinion, it is hard to show any tangible advantage to built-in support for customer's TelemetryModules. Drop 'em! Drop 'em dead!


**Telemetry initializers and Telemetry processors**

I chose to combine these two in a single section, and that's because they are exactly the same thing. I kid you not, and don't take my word for it.

 ```
public interface ITelemetryInitializer
{
        void XXX(ITelemetry telemetry);
}
	
public interface ITelemetryProcessor
{
        void XXX(ITelemetry item);        
}
```

We're trying to give the customer a way of calling custom code on every telemetry item that passes through the pipeline, regardless of whether it was generated by the application or by SDK's modules.

The key issue here is the order and the guarantee of invocation. 

For initializers, we guarantee invocation of every member of the chain, but pretend that the order doesn't matter (even though nothing prevents initializers from overwriting each other's data).

For processors, we guarantee the order of invocation, but invocation itself is not guaranteed (depending on whether someone up the chain has decided to kill the item or not). These are essentially filters.

We need a simple solution to this issue, and I really don't think two separate extension points are necessary here. I would rather suggest something like this:

```
// want to handle telemetry items? Implement this!
public interface ITelemetryHandler
{
      public void HandleTelemetry(ITelemetry telemetry, TelemetryHandlerEventArgs args);
}

// all the information about the handler chain is here
// and you can affect what happens to the item next, too
public class TelemetryHandlerEventArgs
{
    // set this to true to drop the item on the floor
    bool DropTelemetry {set;}

	// all handlers in the chain before and after this one (if it's useful!)
	TelemetryHandlerChain TelemetryHandlersBefore {get;}
	TelemetryHandlerChain TelemetryHandlersAfter {get;}
		
	// use this to interact with other handlers if you need to; this property bag will be passed on along with the item (if it's useful)
	PropertyBag HandlingProperties {get;set;}
}
```

The "implementation" above doesn't handle specifying the order in which handlers are called, but we can certainly address that using one of the well established patterns (like a SequenceNumber property on a handler) without making the customer mess around with SetNext() - that's really an implementation detail. Or maybe we don't even need specifying the order.

Clearly, there are threading-related concerns involved, but it's not really any more complicated than the implementation we have right now.

TelemetryChannel as a handler could be a slight overgeneralization; instead of handling all those special cases, we can probably just have it separately.

With this, we get a single concept (a signle extension point) instead of two, and we get more flexibility. Like @tomasr said, we would probably need a factory to handle all this. We might get a small increase in implementation's complexity here (depending on how flexible we want to be), but that in my opinion would be well worth it, since right now this is the area where the customer might want more control that we actually provide (remember the QuickPulse story).
 
 
Regarding TelemetryChannel and TelemetryConfigurationFactory, I could not possibly agree more; these are awesome changes.

**Comment by tomasr** [comment]
This seems a bit confusing. While I can agree that telemetry processors and initializers share the same signature, wouldn't we want processors to always execute *after* all initializers have run? (I'm assuming you don't want to end up with a processor doing the wrong thing because it was accidentally executed before the right initializer ran).

So in that sense, I still see the value of keeping them separate.

I do like the concept of an ITelemetryHandler as proposed by @tokaplan (though I'd change it slightly), though I'd consider things a bit differently: Basically, you could consider initializers to be a separate abstraction that get executed by a telemetry processor/handler (i.e. think of it as having the first handler in the chain be a TelemetryInitializerProcessor).

As for telemetry modules.... maybe I'm not seeing the full picture, but I never considered them having a reference to the configuration to be such a problem; their problem comes more (imho), from the fact that they are instantiated from the configuration system, rather than the other way around. I don't see any of this addressing this (nor am I clear it should be)

**Comment by abaranch** [comment]
@tokaplan, @tomasr Thank you for your feedback
1. I would agree with @tomasr about TelemetryInitializers. I would like to keeps them though they are kind of obsolete when we have TelemetryProcessors by 2 reasons 1. they are very easy to use and too many people already use it 2. We want them all to be called before TelemetryProcessors as @tomasr mentioned
2. Regarding @tokaplan about Modules I think that worth considering. That looks like an easier thing. But I would still keep an interface so we can create them from config and keep them in the collection of modules
3. For the factory for processors thank you for the proposal. We need to think about it more. Factory that we have now is very complicated, people do not understand that easily and do not remember how to use it without documentation. Rearranging the linked list on the fly would not be a problem 1. I do not expect that to happen. Reorganization needs to happen because we want to support config and in-code support. 2. Even if some items were flowing by one path and you "relink" it dynamically, next item would flow the new way.


If anyone else has comments please post. We are considering all the options now.

**Comment by abaranch** [comment]
One small comment about hiding modules. Yes, we need it because we develop SDK and we need a way to initialize some component. Yes, customers who use SDK does not need to create modules. But we have SDK developers that develop SDK over Core SDK and hey would need it for they same reasons we do. We have several examples where it is used: WCF SDK, Azure SDK.

**Comment by tokaplan** [comment]
@abaranch Yeah good point. You could still argue in favor of having some sort of "OnSDKInitialized" event to which anyone could subscribe (including other SDKs), but I personally don't mind at all leaving the public interface, I'm mostly questioning the subscription channel, which I don't think we need. Inheriting from an empty interface and submitting telemetry through regular TelemetryConfiguration/TelemetryClient is perfectly fine in my opinion.

**Comment by abaranch** [comment]
One small comment about processors for us not to forget when we return back to this issue: we need to simplify (or get rid of) "Use" methods for sampling. It starts getting more overloads and one of the reason is because right now it is extremely difficult to configure processors manually without those extension methods. We should not need them after refactoring.
