### ISSUE TITLE
Error message when no access

### ISSUE THREAD

**Issue by bklooste** [Microsoft/ApplicationInsights-dotnet#229]
Please provide an error message / Insight message ( like the cant read configuration)  when storage folder directory  is unavailable.

**Comment by abaranch** [comment]
We have a warning [message](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/TelemetryChannels/ServerTelemetryChannel/Shared/Implementation/ApplicationFolderProvider.cs#L85)
Since there is no internet connection we cannot send it out to your portal. In F5 this message would be displayed in the VS output window (starting 2.0). On production server you can get it by [collecting traces using perfview](http://sergeysharp.com/blog/2015/04/16/diagnostic-of-applicationinsights-sdk/)
