### ISSUE TITLE
Client-Side cfg script object documentation and Token Header removed

### ISSUE THREAD

**Issue by esyker** [microsoft/ApplicationInsights-dotnet#2369]
I am using Application Insights from Microsoft Azure in ASP.NET Webforms. I created a proxy to redirect the client-side requests in order to protect the API key. It worked fine in a short example I had created. However, when I tried to integrate in my company website, there was a header that was being added to protect other websites from invoking the API. The code to add the header is as follows:

`
var csrfToken = "<%:TokenHeaderValue()%>";
        $(document).ajaxSend(function (ev, jqXHR, settings) {
            if (!settings.url.startsWith("http://127.0.0.1:<%= SGCBusiness.Configuration.AgentManagerPort%>") || IsUserAgentMacOS()) {
                if (settings.url.startsWith("http://127.0.0.1")) {
                    // add userauth token header
                    jqXHR.setRequestHeader('Authorization', 'Bearer ' + getUserAuthToken());
                    if (settings.url.indexOf("?") != -1) {
                        settings.url = settings.url + "&RequestVerificationToken=" + csrfToken;
                    } else {
                        settings.url = settings.url + "?RequestVerificationToken=" + csrfToken;
                    }
                } else {
                    jqXHR.setRequestHeader('RequestVerificationToken', csrfToken);
                }
            }
        });
` 

All the client-side requests get the RequestVerificationToken but the ApplicationInsights script doesn't get this header. I tried to configure the cfg json object adding to Acces-Control Allow-Headers the RequestVerificationToken and even defining the RequestVerificationToken value in the cfg json.
My try can visualized here, please note the cfg json object configuration and my try at the first line of the script to define the csrfToken and then set the token in the header:

`<script>
            cfg: { // Application Insights Configuration
                instrumentationKey: "$key",
                Access- Control - Allow - Headers: ["RequestVerificationToken"],
                RequestVerificationToken: <%:TokenHeaderValue()%>",
                /* ...Other Configuration Options... */
                endpointUrl: "http://localhost:99/api/appinsightsproxy"
            }
        });
    </script>
`

For redability purposes I put the some parts of my try in the first line of the script here:
`
var csrfToken = "<%:TokenHeaderValue()%>";
function(e, t) {
                    if (JSON) {
                        var n = T.fetch;
                        if (n && !y.useXhr) n(t, {
                            method: N,
                            body: JSON.stringify(e),
                            mode: "cors"
                        });
                        else if (XMLHttpRequest) {
                            var a = new XMLHttpRequest;
                            a.open(N, t), a.setRequestHeader('RequestVerificationToken', csrfToken), a.setRequestHeader("Content-type", "application/json"), a.send(JSON.stringify(e))
                        }
                    }
`

I used the documentation presented in this link to try to solve this problem:
[https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript).

However much documentation is not given about the cfg json object. Even the endpointUrl property was discovered in a [github link](https://github.com/shaneochotny/ApplicationInsights-JS-Proxy) (set the proxy as endpointUrl), but even this important endpointUrl property isn't defined in the documentation above.

Two Questions:
.Any idea how can I solve the problem of the RequestVerificationToken and can be this done using the cfg json object?
.Where can I find the proper documentation for the properties of the cfg json object?  

  [1]: https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript
  [2]: https://github.com/shaneochotny/ApplicationInsights-JS-Proxy

**Comment by MSNev** [comment]
Hi, I'm from the AI JS Sdk team and I'll try and answer your questions.

Ok, this turned into a long response...

Let me start by saying that I do understand ```why``` you are trying to "protect" instrumentation key, but it's really not necessary as the instrumentation key on it's own does not grant a bad actor any "special" privilege's beyond sending telemetry into your backend. And if there is a bad actor attempting to "overload" your telemetry, then using this proxy style telemetry forwarding doesn't really save you (even with CSRF protection) as a determined actor can just as easily work around this are they would if they didn't need to. As generally, if this was to occur they would be using some sort of automation and in that case they can just load you page and with a little bit of JavaScript (or HTML scraping) they can still get you CSRF token (and cookie) and send telemetry "through" your server -- So now, not only is there excessive telemetry in Azure Monitor you will also have all of the extra CPU load and network traffic on the servers (which if hosted is even more cost).

## But onto answer your questions

### ___First the easy one___
* the ```cfg``` for the snippet configuration is mostly documented, but probably not as you might expect, this is because [it is really just main configuration](https://github.com/Microsoft/ApplicationInsights-JS#configuration).
  * The main reason this reference doesn't include the ```endpointUrl``` is because generally this does not need to be configured as it is either derived from the ```connectionString``` or it uses the default values.
  * But for reference [here is the location of the ```IConfigutation``` object](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts) which is what this ```cfg``` value is (more below).
 * Adding ```Acces-Control``` ```Allow-Headers``` the ```RequestVerificationToken``` and even defining the ```RequestVerificationToken``` to the cfg json -- This will all be ignored because we read, expect and use only the defined values see point above

### ___Ok the not so easy one___
* Why? -- Let me come back to this...
* First an assumption from what you have provided, Following your provided code you are effectively creating your own pollyfill style intercepting for fetch and XHR add your CSRF token as a header. The problem I see here is that this will work fine for "sending" your own telemetry directly to you server (using this function) but it won't work for the internal ajax tracking that Application Insights performs (as it uses it's own instances) -- we intercept and override the ```prototype``` values of ```XMLHttpRequest``` and completely replace the ```fetch``` function.
  * This approach could almost work if you hooked the prototype instances, but would be extremely fragile. And it would require that you apply the hooks / polyfill implementation BEFORE the Snippet is executed otherwise the hooks that ApplicationInsights puts in place will bypass your overrides.

### And now we start getting a little more complicated, but maybe easier for you...
So, above I mentioned that the ```cfg``` object is actually an ```IConfigutation``` object](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts) (which it is) -- but, for the purposes of the internal ```Sender``` it is also merged and [considered to be an ```IConfig```](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Interfaces/IConfig.ts) object. (ie. it can contain named properties from both) and this object includes [an optional "map" called ```customHeaders```](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Interfaces/IConfig.ts#L429) which can be defined in the ```cfg``` with your ```RequestVerificationToken``` value and I believe (not tried) that this will automatically added the extra headers to any ```fetch``` or ```XMLHttpRequest``` request that the SDK makes to send the telemetry to your front end.

So it __should__ look something like

```js
<script>...
 cfg: { 
   instrumentationKey: "$key", 
   endpointUrl: "http://localhost:99/api/appinsightsproxy" 
   customHeaders: {
      "RequestVerificationToken": <%:TokenHeaderValue()%>"
    }, 
    /* ...Other Configuration Options... */ 
  }
}); </script>
```

## Ok now back to the ___Why___

### As it's a little more complicated...

* Depending on the browser that your users are using the AI JS Sdk will use either ```fetch```, ```XMLHttpRequest```, ```XDomainRequest``` (IE 9 or less) or ```sendBeacon```
* The above solution (or a polyfill) will work for both ```fetch``` or ```XMLHttpRequest``` sending to your front end BUT (and they are big ones) 
  * If you have any user on IE 9 or below the SDK will use ```XDomainRequest``` which DOESN'T support custom headers, so there is no way to send your CSRF Token as a header thus any validation you put in place will drop the request.
  * And if your users are using more modern browsers 😄 (right -- not so fast), during page unload (```unload```, ```pagehide```, ```visibilitychange``` and ```beforeunload``` events) the SDK uses (if available) the ```sendBeacon()``` API to send the request as synchronous XHR requests from modern the browser are now blocked during the "unloading" cycle in preference of ```sendBeacon()``` (or ```fetch``` with ```keepAlive``` (currently chrome experiential only)). ___BUT___, ```sendBeacon``` also does NOT allow custom headers, so again any validation on your server to validate the CSRF token based on the additional header will fail!.

The only "work-around" for the ```XDomainRequest``` and ```sendBeacon()``` issues would be to pass your CSRF token as a query-string parameter, with all of the issues associated with that (potentially getting logged by proxies etc -- but with the associated cookie that you should also have you may find this ok). Thus this would be a case of adding it to the ```endpointUrl``` config value.

Cheers

Nev

**Comment by esyker** [comment]
> Hi, I'm from the AI JS Sdk team and I'll try and answer your questions.
> 
> Ok, this turned into a long response...
> 
> Let me start by saying that I do understand `why` you are trying to "protect" instrumentation key, but it's really not necessary as the instrumentation key on it's own does not grant a bad actor any "special" privilege's beyond sending telemetry into your backend. And if there is a bad actor attempting to "overload" your telemetry, then using this proxy style telemetry forwarding doesn't really save you (even with CSRF protection) as a determined actor can just as easily work around this are they would if they didn't need to. As generally, if this was to occur they would be using some sort of automation and in that case they can just load you page and with a little bit of JavaScript (or HTML scraping) they can still get you CSRF token (and cookie) and send telemetry "through" your server -- So now, not only is there excessive telemetry in Azure Monitor you will also have all of the extra CPU load and network traffic on the servers (which if hosted is even more cost).
> 
> ## But onto answer your questions
> ### _**First the easy one**_
> * the `cfg` for the snippet configuration is mostly documented, but probably not as you might expect, this is because [it is really just main configuration](https://github.com/Microsoft/ApplicationInsights-JS#configuration).
>   
>   * The main reason this reference doesn't include the `endpointUrl` is because generally this does not need to be configured as it is either derived from the `connectionString` or it uses the default values.
>   * But for reference [here is the location of the `IConfigutation` object](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts) which is what this `cfg` value is (more below).
> * Adding `Acces-Control` `Allow-Headers` the `RequestVerificationToken` and even defining the `RequestVerificationToken` to the cfg json -- This will all be ignored because we read, expect and use only the defined values see point above
> 
> ### _**Ok the not so easy one**_
> * Why? -- Let me come back to this...
> * First an assumption from what you have provided, Following your provided code you are effectively creating your own pollyfill style intercepting for fetch and XHR add your CSRF token as a header. The problem I see here is that this will work fine for "sending" your own telemetry directly to you server (using this function) but it won't work for the internal ajax tracking that Application Insights performs (as it uses it's own instances) -- we intercept and override the `prototype` values of `XMLHttpRequest` and completely replace the `fetch` function.
>   
>   * This approach could almost work if you hooked the prototype instances, but would be extremely fragile. And it would require that you apply the hooks / polyfill implementation BEFORE the Snippet is executed otherwise the hooks that ApplicationInsights puts in place will bypass your overrides.
> 
> ### And now we start getting a little more complicated, but maybe easier for you...
> So, above I mentioned that the `cfg` object is actually an `IConfigutation` object](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCore/src/JavaScriptSDK.Interfaces/IConfiguration.ts) (which it is) -- but, for the purposes of the internal `Sender` it is also merged and [considered to be an `IConfig`](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Interfaces/IConfig.ts) object. (ie. it can contain named properties from both) and this object includes [an optional "map" called `customHeaders`](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Interfaces/IConfig.ts#L429) which can be defined in the `cfg` with your `RequestVerificationToken` value and I believe (not tried) that this will automatically added the extra headers to any `fetch` or `XMLHttpRequest` request that the SDK makes to send the telemetry to your front end.
> 
> So it **should** look something like
> 
> ```js
> <script>...
>  cfg: { 
>    instrumentationKey: "$key", 
>    endpointUrl: "http://localhost:99/api/appinsightsproxy" 
>    customHeaders: {
>       "RequestVerificationToken": <%:TokenHeaderValue()%>"
>     }, 
>     /* ...Other Configuration Options... */ 
>   }
> }); </script>
> ```
> 
> ## Ok now back to the _**Why**_
> ### As it's a little more complicated...
> * Depending on the browser that your users are using the AI JS Sdk will use either `fetch`, `XMLHttpRequest`, `XDomainRequest` (IE 9 or less) or `sendBeacon`
> * The above solution (or a polyfill) will work for both `fetch` or `XMLHttpRequest` sending to your front end BUT (and they are big ones)
>   
>   * If you have any user on IE 9 or below the SDK will use `XDomainRequest` which DOESN'T support custom headers, so there is no way to send your CSRF Token as a header thus any validation you put in place will drop the request.
>   * And if your users are using more modern browsers 😄 (right -- not so fast), during page unload (`unload`, `pagehide`, `visibilitychange` and `beforeunload` events) the SDK uses (if available) the `sendBeacon()` API to send the request as synchronous XHR requests from modern the browser are now blocked during the "unloading" cycle in preference of `sendBeacon()` (or `fetch` with `keepAlive` (currently chrome experiential only)). _**BUT**_, `sendBeacon` also does NOT allow custom headers, so again any validation on your server to validate the CSRF token based on the additional header will fail!.
> 
> The only "work-around" for the `XDomainRequest` and `sendBeacon()` issues would be to pass your CSRF token as a query-string parameter, with all of the issues associated with that (potentially getting logged by proxies etc -- but with the associated cookie that you should also have you may find this ok). Thus this would be a case of adding it to the `endpointUrl` config value.
> 
> Cheers
> 
> Nev

Thank you for your answer!
I have the cfg object as follows: 
`
cfg: { // Application Insights Configuration
                instrumentationKey: "$key",
                customHeaders: {
                    "RequestVerificationToken": csrfToken
                },
                /* ...Other Configuration Options... */
                endpointUrl: "http://localhost:99/api/appinsightsproxy"
            }
`

However the custom header was not added. You can easily try it by yourself to verify it!
Is this any type of bug? Or am I possibly doing anything wrong? Can you verify if you can add the custom header yourself  this way?

**Comment by MSNev** [comment]
Yep may bad, I misread the code when responding, on creating a sample (and it failing) I took a closer look and the code that uses this value and it is in fact an array of objects rather than an map. So the correct config (which I have now tested) is

```js
    cfg: { // Application Insights Configuration
        instrumentationKey: "INSTRUMENTATION_KEY",
        endpointUrl: "http://localhost:99/api/appinsightsproxy",
        customHeaders: [
            { header: "RequestVerificationToken", value: csrfToken }
        ]
    }});
```

**Comment by esyker** [comment]
Yep it seems to work!
However only the posts made by InstrumentHooks.js ( [https://js.monitor.azure.com/shared/AppInsightsCore/dist-esm/JavaScriptSDK/InstrumentHooks.js](https://js.monitor.azure.com/shared/AppInsightsCore/dist-esm/JavaScriptSDK/InstrumentHooks.js))   are accepted ! The posts made by Sender.js (  [https://js.monitor.azure.com/channels/applicationinsights-channel-js/dist-esm/Sender.js](https://js.monitor.azure.com/channels/applicationinsights-channel-js/dist-esm/Sender.js)) are not accepted!
I am getting the pageViews in the portal, however those posts by Sender.js are being rejected which should affect some metrics!

**Comment by MSNev** [comment]
Looking at the image the rejected "403" response is coming from a "ping" request... The AI SDK doesn't send "ping" requests, however, line 414 of the unminified version of sender.js this aligns with the usage of the ```sendBeacon``` API (so this is possibly one of the unload / navigate away ```BUT's``` that I mentioned above) -- ie. ```sendBeacon``` doesn't support adding additional headers, so it won't have your header.
