### ISSUE TITLE
Microsoft.Data.SqlClient.SqlConnection' threw an exception with SnapshotCollector 1.4.0 and 1.4.1

### ISSUE THREAD

**Issue by didaskein** [microsoft/ApplicationInsights-dotnet#2424]
No issue with the version : 1.3.7.5 of Microsoft.ApplicationInsights.SnapshotCollector

Since the upgrade to 1.4.0 (and same error with 1.4.1)

When we call EF core call to the SQL DB we get this error message : 

System.TypeInitializationException: 'The type initializer for 'Microsoft.Data.SqlClient.SqlConnection' threw an exception.'
ArgumentException: Delegates must be of the same type.

   at System.MulticastDelegate.CombineImpl(Delegate follow)
   at System.Runtime.Loader.AssemblyLoadContext.add__unloading(Action`1 value)
   at System.Runtime.Loader.AssemblyLoadContext.add_Unloading(Action`1 value)
   at Microsoft.Data.SqlClient.SqlDiagnosticListener..ctor(String name)
   at Microsoft.Data.SqlClient.SqlConnection..cctor()

![image](https://user-images.githubusercontent.com/13362276/134742256-8bc7ddbe-72c3-4b29-90ef-3280655d0adb.png)

Thank you ! :-)

**Comment by cijothomas** [comment]
If you encounter an issue with [Application Insights Snapshot Debugger](https://docs.microsoft.com/azure/azure-monitor/app/snapshot-debugger) in Azure, please check the [troubleshooting documentation](https://docs.microsoft.com/azure/azure-monitor/app/snapshot-debugger-troubleshoot). Use the [Azure Support Center](https://azure.microsoft.com/support/create-ticket/) to file a ticket if the troubleshooting document didn't help.

Otherwise, please [file an issue](https://github.com/microsoft/ApplicationInsights-SnapshotCollector/issues/new/choose) in the Microsoft/ApplicationInsights-SnapshotCollector repo.
