### ISSUE TITLE
Out of memory exceptions due to multiple TelemetryClients & TelemetryConfiguration  Creation

### ISSUE THREAD

**Issue by yanivyd** [Microsoft/ApplicationInsights-dotnet#253]
Our service (WebApp built of multiple web jobs & queues) relay extensively on AI TelemetryCleint. 
Currently we create a new TelemetryClient per queue message processing flow (In order to set a SessionID which allowa us to correlate all of our traces\exceptions\etc.):

Queue Message handler:
var telemetryClient = new TelemetryClient();
telemetryClient.Context.Session.Id = sessionId;
…
                telemetryClient.TrackTrace(“..”);
       …
       telemetryClient.Flush();

Last week we had an incident due to OutOfMemoryExceptions after a change we did in the way we create our clients: 
We started creating a new TelemetryConfiguration per new client (Per queue message). Since these “configurations” contain a Channel, and are not disposed automatically – our service started getting OutOfMemory exceptions.
To solve the issue we created several static configurations and used them in our clients.

Few questions I will appreciate if you can answer:
1.  Is there a problem with creating multiple clients?
2.  I see that the TelemetryClient isn’t IDisposable, so I assume we do not need to dispose the clients actively. Please correct me if I’m wrong.
3.  What’s the best way to maintain correlation between items. Is it really by creating a new telemetry client and setting a session Id?
4.  Is it correct that we may get OOM exceptions since we didn’t actively dispose the configurations?
a.  IMHO - The name “configuration” is misleading, since a user might not realize by the name that it’s an object contains a streaming channel, and should be disposed.
b.  Perhaps we can add a documentation over TelemetryClient’s ctors, which warns the user that the TelemetryConfiguration object should be disposed after usage.

Will appreciate your response

**Comment by dnduffy** [comment]
Typically you would only need one (singleton) TelemetryClient instance since it is thread safe and can be reused.  However, you can create multiple instances if you need to.
You could use an initializer to set your correlation from an HttpContext variable.
See this blog post under "Correlation" to see an approach for correlating with the current request: [https://azure.microsoft.com/en-us/blog/save-money-with-application-insights-web-sdk-2-0/](https://azure.microsoft.com/en-us/blog/save-money-with-application-insights-web-sdk-2-0/)

**Comment by dsschnau** [comment]
I came across this ticket digging into why I was getting Memory Exceptions running a new'd up `TelemetryClient` with each request to one of my APIs.

Turns out `TelemetryClient` doesn't implement `IDisposable`, but `TelemetryConfiguration` **does**. So you have to make sure to dispose of it with a using statement or a finally block.

**Comment by SergeyKanzhelev** [comment]
New-ing up `TelemetryConfiguration` a lot is not a good idea. It is the best to create new `TelemetryClient` with the same configuration over and over again. This way the same channel will be used for each client. And telemetry upload will fully utilize batching and other optimizations.

**Comment by SergeyKanzhelev** [comment]
I'm sorry you hit the problem. Did you follow some documentation that suggests to create multiple channels? Perhaps you have a suggestion how to make this clearer?

**Comment by SergeyKanzhelev** [comment]
I love maintenance programming. Hope you enjoy it too. Thank you for using Application Insights!

**Comment by pjt33** [comment]
@SergeyKanzhelev,

> I'm sorry you hit the problem. Did you follow some documentation that suggests to create multiple channels? Perhaps you have a suggestion how to make this clearer?

I've found this thread from a Google search for `TelemetryClient dispose`. It never ever occurred to me that `TelemetryConfiguration` might be `IDisposable`: the name `FooConfiguration` implies to me that it's a collection of named ints and strings and doesn't "own" anything. Renaming the class to something which suggests ownership of I/O resources could help.
