### ISSUE TITLE
ApplicationInsightsLogger doesn't respect Category LogLevel

### ISSUE THREAD

**Issue by stevendarby** [microsoft/ApplicationInsights-dotnet#2653]
As per https://github.com/dotnet/aspnetcore/issues/42950 I have added the following to my appsettings.json `Logging:LogLevel` section in order to filter out logging by the ASP.NET Core ExceptionHandlerMiddleware: `"Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware": "None"`

I can confirm this works for the ConsoleLogger. However, I'm still seeing exceptions tracked in application insights with the category "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware" which suggests to me that the app insights logger isn't respecting its configured log level.

I can provide a repo if really needed.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-do-i-customize-ilogger-logs-collection

**Comment by stevendarby** [comment]
I'm not clear on what this means. There is no example for targeting a category, which might help. Are you saying that the application insights logger doesn't respect the standard way of configuring log levels. Isn't that a bug?

**Comment by stevendarby** [comment]
So, what I had previously, which didn't work:

```JSON
 "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware": "None" 
    }
  }
```

and now this, which does seem to work:

```JSON
 "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware": "None" 
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware": "None"
      }
    }
  }
```

I want to apply the category filter to all loggers, so I need to keep it in the general section too. The duplication is unfortunate.

I also don't quite understand the justification for requiring an explicit override for the ApplicationInsights logger which is given in your link:

`It doesn't capture it because the SDK adds a default logging filter that instructs ApplicationInsights to capture only Warning logs and more severe logs. ApplicationInsights requires an explicit override.`

Why does this prevent the LogLevel for the specific category - applied in the general section - being applied to the application insights logger? Thanks in advance for any further info.

**Comment by cijothomas** [comment]
> Why does this prevent the LogLevel for the specific category - applied in the general section - being applied to the application insights logger?

If you used Microsoft.ApplicationInsights.AspNetCore package, and enabled application insights using the one liner services.AddApplicationInsightsTelemetry(), then it automatically inserts a Filter rule to only send Warning or above to ApplicationInsightsLoggerProvider. Since this is a specific rule, it wins over the general one you have. Hence you need to give more specific filter to override.

**Comment by javedali-dev** [comment]
> It doesn't capture it because the SDK adds a default logging filter that instructs ApplicationInsights to capture only Warning logs and more severe logs. ApplicationInsights requires an explicit override.

I want to send all the log don't want to app insight to apply the filter. Any idea how to fix this?

**Comment by gioce90** [comment]
I think the request here is (please @stevendarby correct me if I'm wrong): you _have to_ write the `"Logging":"ApplicationInsights":"LogLevel"` section, rather than just the `"Logging":"LogLevel"` section.

Normally, a provider such as AppInsights, _when not otherwise specified_, is expected to use what is written in the common section `"Logging":"LogLevel"`. 

But, if we write something like:

```
 "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "My.Example": "Trace" 
    }
  }
```

... sadly the traces with `"My.Example"` category would not be logged.
But if we do something like: 

```
 "Logging": {
    "LogLevel": {
      "Default": "Warning"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "My.Example": "Trace"
      }
    }
  }
```
... this works.

I think the problem here is that, by default, ApplicationInsights use "Warning" as [default severity level](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2610). If you don't specify the `"Logging":"ApplicationInsights":"LogLevel"` config section, the _"warning" filter rule_ will overwrite the rules in `"Logging":"LogLevel"`.

**Comment by cijothomas** [comment]
> Normally, a provider such as AppInsights, when not otherwise specified, is expected to use what is written in the common section "Logging":"LogLevel".

^ This is true for application insights logger provider as well.

**Comment by cijothomas** [comment]
> I think the problem here is that, by default, ApplicationInsights use "Warning" as

^ This is not the behavior of ApplicationInsightsLoggingProvider. It is the case when you use Microsoft.ApplicationInsights.AspNetCore package, to enable all telemetry (tracing, logging, metrics, etc.) with a one-liner (AddApplicationInsightsTelemetry()).

**Comment by rwb196884** [comment]
So: if I use `AddApplicationInsightsTelemetry` then the normal logging configuration gets ignored.

This is a very nasty boobytrap.

What is the recommended workaround to get logging working?

**Comment by gioce90** [comment]
> So: if I use `AddApplicationInsightsTelemetry` then the normal logging configuration gets ignored.
> 
> This is a very nasty boobytrap.
> 
> What is the recommended

A couple of years are passed, but if I remember correctly, isn't totally ignored, but ApplicationInsights use "Warning" as default filter on top. 
So to avoid that (again, if I remember correctly)  you should set a lower filter level in "Logging:ApplicationInsights:LogLevel":"Default", as wrote here : https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#ilogger-logs
