### ISSUE TITLE
Telemetry with empty properties collection is dropped

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet#319]
```
            var properties = new Dictionary<string, string>
            {
                {"UserId", ""}
            };
            new TelemetryClient().TrackException(new ApplicationException(), properties);
```

Invalid json, no "," after properties collection.
 

> Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.XXX.Exception","time":"2016-09-30T23:35:56.1080471Z","iKey":"XXX","tags":{"ai.internal.sdkVersion":"dotnet:2.2.0-31572","ai.operation.id":"/buMs/VxSMI=","ai.operation.name":"GET /Default","ai.operation.parentId":"/buMs/VxSMI=","ai.device.roleInstance":"ZZZ.redmond.corp.microsoft.com"},"data":{"baseType":"ExceptionData","baseData":{"ver":2,"handledAt":"UserCode","properties":{}"exceptions":[{"id":31494208,"typeName":"System.ApplicationException","message":"Error in the application.","hasFullStack":true}]}}}

**Comment by hallatore** [comment]
I think the bug is here: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/37cec526194b833f7cd676f25eafd985dd88d3fa/src/Core/Managed/Shared/Extensibility/Implementation/JsonWriter.cs#L164

It only adds comma to properties with values. But since it strips out null, etc it ends up writing the property but never the comma.
