### ISSUE TITLE
How does ServerTelemetryChannel handle multiple instances retrying against the same file?

### ISSUE THREAD

**Issue by anblanco** [Microsoft/ApplicationInsights-dotnet#331]
Context:
I have a WebApp that I'd like to use ServerTelemetryChannel for. I understand that I can persist any temporary files to the WebApps durable directory d:\home\, and every instance of the WebApp will have R/W access to the files in that path. 

When I scale out to multiple instances and each of them are retrying against the same temporary files, what is the expected behavior of ServerTelemetryChannel? Will it correctly dequeue each item only once?

**Comment by anblanco** [comment]
When I look at the code in TransmissionStorage, it appears that the code is correctly account for race conditions where multiple threads are trying to access the same file and that file is locked.

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/TelemetryChannels/ServerTelemetryChannel/Shared/Implementation/TransmissionStorage.cs#L176

In relation to my question: would it be correct to state that ServerTelemetryChannel will gracefully handle multiple instances trying to process the same serialized telemetry file?

**Comment by dnduffy** [comment]
Yes and sort of.  There is no cross process mutex at the moment so if you have multiple processes sharing an InstrumentationKey and writing to and from the same folder there may be some conflict and they will raise and log the issue internally but should not have serious issues.  If you do find a problem (such as CPU % or drive usage) I would love to have more details though since I just finished trying to make that code more stable.
As for scaling, I would generally scale out by having multiple instances on different machines/VM's rather than on the same machine/VM because ASP.NET is already capable of handling multiple concurrent requests from a single instance.
Within an instance of your application the ServerTelemetryChannel should be completely thread safe and will be safely processing any transmissions that were temporarily saved to storage with up to three parallel threads (three just happens to be the default limit).

**Comment by SergeyKanzhelev** [comment]
@anblanco one alternative you have is to set [StorageFolder](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/TelemetryChannels/ServerTelemetryChannel/Shared/ServerTelemetryChannel.cs#L168) to some process-specific location. For instance to the `%LocalAppData%\PID\InstrumentationKey` This will help to minimize the overhead of race conditions checks

**Comment by anblanco** [comment]
Okay, I think I'm seeing the picture. Here is how I understand ServerTelemetryChannel would work in a Web App.

The main goal I'm looking for is reliably ensuring I can retry telemetry data. In this case I'm not too worried about the performance overhead.

- By default, a WebApp's %LocalAppData% and %TMP% point to a non-persistent mapped drive called D:\local.  I would like to persist telemetry so I choose to point the persistent storage at D:\home. 
- When I scale out in WebApps, I get multiple VM instances. Each of those instances has access to the mapped drive at D:\home
- There is no cross process mutex, but given that the code checks on IOException (file locked), each process and it's threads process the files correctly

And to Sergey's point, if I have performance issues I can always use the %LocalAppData% w/ a process specific path to prevent multiple processes from interfering w/ each other. Using %LocalAppData% means I may lose data when the VM is no longer running the app, but that's a tradeoff decision I can make between reliability of data vs performance.

Thank you @SergeyKanzhelev  and @dnduffy for the clarification and new information!

Source for Web Apps file system restrictions: https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#file-system-restrictionsconsiderations
