### ISSUE TITLE
TrackTrace without flush causes an OOM exception

### ISSUE THREAD

**Issue by haniamr** [Microsoft/ApplicationInsights-dotnet#345]
Version: "Microsoft.ApplicationInsights" 2.1.0.
Repro of the issue:
```
TelemetryConfiguration config = TelemetryConfiguration.CreateDefault();
config.InstrumentationKey = "{KEY}";

TelemetryClient client = new TelemetryClient(config);
var dictionary = new Dictionary<string, string>()
            {
                {"testprop", "testval" },
                {"testprop2", "testval2" },
                {"testprop3", "testval3" },
            };

Parallel.For(0, 10000000, (i) =>
            {
                client.TrackTrace("test " + i, SeverityLevel.Information, dictionary);
            });
```

This code will throw an out of memory exception when running in a 32-bit process, and eventually consume up to 21GB+ of RAM when running in a 64-bit process.

Here's a snapshot of the memory usage when profiling:
![image](https://cloud.githubusercontent.com/assets/5480153/19888858/3fa46884-a029-11e6-8e2c-41bca7a0f839.png)

When I call Flush(), the issue is resolved, but shouldn't the SDK flush the buffer automatically based on some criteria as mentioned in the documentation? https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/#_flushing-data

**Comment by cijothomas** [comment]
Took a look at InMemoryChannel - we already have logic to flush events once it reaches buffer capacity which is 500 items by default. There is a flush every 30 secs as well.
The above repro is sending 10million events and this is more than backend can accept, and can likely cause OOM as channel cannot dispatch that many events.

**Comment by dnduffy** [comment]
I don't think this is a backend problem, the backend will reject too many items and the InMemoryTransmitter should drop failures on the floor.  So something is queuing up items in memory faster than it can figure out what to do with them.  We need to run the repro and look at the memory profile to see where the objects got "stuck".  In the InMemoryChannel it just calls Enqueue on the TelemetryBuffer which will call the OnFull callback which in turn causes the AutoResetEvent in the InMemoryTransmitter to be set.  The InMemoryTransmiter will try to dequeue and send the items in the buffer but meanwhile the buffer will still be accepting items when maybe it should start dropping items if it crosses a higher threshold and until it is below that safety threshold again.  The tradeoff here would be that currently the buffer would slowly drain after a burst of data and not lose any but to protect against overload it would have to drop some of the data.  Arguably this should not be a problem because the backend will drop items when the count is over 32K per minute by default (unless a customer is paying for more).

**Comment by haniamr** [comment]
@cijothomas If by backend you mean the App Insights backend, in fact the above code runs successfully if I manually call Flush() so I think the problem is in the SDK's auto flushing mechanism.

The above repro is indeed an exaggeration, but I faced the same issue in a Web Service that consumes a lot of memory with thousands of requests and I had to do a manual flush to overcome this issue.

**Comment by cijothomas** [comment]
Channel needs to be fixed to simply drop items if items are added at a faster rate than it can dispatch to backend.

**Comment by dnduffy** [comment]
@cijothomas Let's discuss this morning, it's not as simple as that.

**Comment by cijothomas** [comment]
Based on my experiments so far:
When you make millions of Track() call using Parallel.For() we hit OOM. The logic to flush items from buffer when its full is simply 'signalling' that the Thread responsible for flushing items is ready to be run. However, this thread does not get a chance to be actually scheduled, because threadpool is too busy with the requests from Parallel.For(). So the buffer never gets emptied, and eventually we hit OOM.
When you use Flush() explicitly, this goes and runs the logic to flush items synchronously, instead of simply signalling a thread to run flush logic. Flush() is a blocking call.

 InMemoryChannel needs some protection to simply drop items, if there items in queue reaches a number which is n times capacity. (By capacity, i mean the flush threshold i.e the number of items after which a flush is signalled)

**Comment by cijothomas** [comment]
I'll make changes to protect SDK from hitting OOM by dropping items above a HardThreshold.(unlike capacity)

**Comment by cijothomas** [comment]
@haniamr - Did you face the issue with InMemoryChannel or ServerChannel?

**Comment by haniamr** [comment]
@cijothomas I'm not quite sure I understand the question, the code I used looked similar to the one in the above repro... Is this something I should/can know from somewhere?

**Comment by cijothomas** [comment]
@haniamr Never mind about the channel, as the logic is similar. (btw you can look at ApplicationInsights.config of you app to see the TelemetryChannelused.)
