### ISSUE TITLE
There should be a kill switch that completely disables Application Insight event collection

### ISSUE THREAD

**Issue by AllanXu49** [Microsoft/ApplicationInsights-dotnet#397]
Currently there are two options to disable Application Insight:

Option 1: TelemetryConfiguration.Active.DisableTelemetry = true;

Option 2: Comment instrumentation key in the config file

With both of above options Application Insight keeps collecting events, but it does not upload them. Means there is (potentially slight) performance overhead.

There should be an option to completely disable Application Insight SDK when it is required.

**Comment by SergeyKanzhelev** [comment]
Is the main concern a performance impact? Or temporary disable collection? Or anything else?

Note, commenting the key in configuration file will require the process restart when setting something in code will not. However setting in code may be too late for some in-revertable changes. Like loading and http module or listening of certain events. Please describe your scenarios and requirements in terms of restart requitement/re-enablement on the flight, etc. Also how much of performance overhead would be acceptable?

**Comment by dnduffy** [comment]
Setting DisableTelemetry in the configuration will cause the TelemetryClient.Track call to do nothing, it's not even collecting events, they will not be stored in a buffer anywhere.  There is still some method call overhead before the check is made but you can't completely get rid of that at run time.  The only way to completely remove Application Insights so that there is absolutely zero run time overhead would be to remove it from being configured in your application.  If you just want to turn it off temporarily then setting DisableTelemetry to true will do that and is the most appropriate option for run time configuration that doesn't recycle the app pool.

**Comment by SergeyKanzhelev** [comment]
@dnduffy I was thinking that our standard telemetry modules should monitor and respect the DisableTelemetry flag when possible. For many modules it wouldn't be a problem at all.

**Comment by AllanXu49** [comment]
Hi Sergey,

Sorry I am noticing that I did not respond to your question.

The main concern is performance. If this is not a valid concern, please let me know.

Being able to disable AI without any re-compile is important when we need to deploy (sell) the application to multiple customers - some might prefer not using AI.

**Comment by kulkarnisachin07** [comment]
Hi,
Can we keep the AI settings in web.<profile>.config file, so that we can enable it to for specific deployemenys.
Only concern I have, is if this is way, then which settings we need to keep? 
Please validate if following settings in web.config are sufficent to disable/enable AI? 
Also will it be right thing to do from performance point of view?
1. Under <System.Web>
<httpModules>
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" />
    </httpModules>

2. Under <system.webServer>
<modules runAllManagedModulesForAllRequests="true">
    <remove name="ApplicationInsightsWebTracking" />
    <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
  </modules>
3. Under <system.diagnostics>
<trace autoflush="true" indentsize="0">
<listeners>
<add name="myAppInsightsListener" type="Microsoft.ApplicationInsights.TraceListener.ApplicationInsightsTraceListener, Microsoft.ApplicationInsights.TraceListener" />
</listeners>
</trace>
</system.diagnostics>

**Comment by SergeyKanzhelev** [comment]
@kulkarnisachin07  you have couple options. Easiest is to have `InstrumentationKey` set only for certain environments. If the key is not set for the environment - telemetry will not be set and it is virtually disabled.

Alternatively you can keep it in application settings and have a code like this in the very beginning of the application:
```
TelemetryConfiguration.Active.DisableTelemetry = IsTelemetryDisabled();
```

**Comment by SergeyKanzhelev** [comment]
This should be implemented by specific telemetry modules. Opened issues in corresponding repositories. Closing the issue in this repo

**Comment by fleed** [comment]
@SergeyKanzhelev is "setting the instrumentation key to empty value" equivalent to "set TelemetryConfiguration.Active.DisableTelemetry = true"? Is there any additional performance penalty to pay?
