### ISSUE TITLE
Microsoft.AppInsights.dll failing to load for .net version 4.6.1

### ISSUE THREAD

**Issue by nevedita** [Microsoft/ApplicationInsights-dotnet#404]
Hi,

I am trying to load Microsoft.ApplicationInsights.dll which I got from the Net46 folder of the [Nuget package ](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web) on a Windows 7 machine which has .Net 4.6.1 installed. I am getting the following error:

Exception calling "LoadFile" with "1" argument(s): "This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded. (Exception from HRESULT: 0x8013101B)"_

Which dll version will work on this machine?

This step is failing for me:
 $AI = "$global:scriptRoot\Microsoft.ApplicationInsights.dll"
 [Reflection.Assembly]::LoadFile($AI)

Thanks!

**Comment by SergeyKanzhelev** [comment]
Check the runtime version of the powershell host. Most probably on Windows 7 it is running under FW 2.0. See [this](https://blogs.technet.microsoft.com/rmilne/2016/05/18/azure-ad-module-this-assembly-is-built-by-a-runtime-newer-than-the-currently-loaded-runtime-and-cannot-be-loaded/) for example

**Comment by SergeyKanzhelev** [comment]
As turned out in offline conversation - this is indeed the case. PowerShell is running under the framework 2.0 even though 4.6.1 is installed on computer.

Since Application Insights doesn't support framework 2.0 - you have four options:
1. Build your own ApplicationInsights.dll 
2. Start a separate process from PowerShell under the correct framework version
3. Require to install and run powershell 3.0+
4. Force powershell to run under FW 4.0 like described here http://stackoverflow.com/questions/2094694/how-can-i-run-powershell-with-the-net-4-runtime

**Comment by nevedita** [comment]
Thanks Sergey. Option 4 works for me. Thanks for the prompt reply on this.
