### ISSUE TITLE
Reconcile BaseIntermediateOutputPath handling between -dotnet and -dotnet-logging repos

### ISSUE THREAD

**Issue by karolz-ms** [Microsoft/ApplicationInsights-dotnet#490]
This repo and the -dotnet-logging repo are using a different solution to the problem described in https://github.com/Microsoft/msbuild/issues/1603#issuecomment-283104367 

This repo manually ensures that BaseIntermediateOutputPath is set before Microsoft.Common.props is loaded. The -dotnet-logging repo is using a Directory.Build.props file (technically, will be using this file when https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/77 is merged)

We should make it consistent between the two repos. My (karolz) slight preference would be to use Directory.Build.props as it allows the project file to use the standard structure.

**Comment by pharring** [comment]
I'll take a look at this. I like the idea of keeping the standard project file structure.

**Comment by karolz-ms** [comment]
Super, thanks a bunch @pharring !

**Comment by pharring** [comment]
This is fixed now, but I had to workaround an issue with gitlink (it insists on using MSBuild 4.0 tools). I notice that gitlink 3.0.0 has moved to a model where it is integrated with the build (.props and .targets) instead of just calling out to an EXE. That version is in preview but we could switch to it when it is stable and remove the workaround..
