### ISSUE TITLE
[Metrics] Metric aggregation do not respect the roleName and roleInstace of requests and dependencies

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#491]
Metric pre-aggregation should respect roleName and roleInstance context properties of the requests and dependencies it pre-aggregates to support multi-tenant scenarios when a single process runs multiple roles (service fabric scenario)

**Comment by SergeyKanzhelev** [comment]
cc: @macrogreg

**Comment by macrogreg** [comment]
@SergeyKanzhelev I would suggest to close this particular issue because the scenarios we support for metric aggregation currently do not require it. There is a ton on dimensions we _could_ use, but we use only those that are required by currently supported per-aggregation scenarios. Why are these special?

What are your thoughts on this?

**Comment by SergeyKanzhelev** [comment]
In case of Service Fabric application the same appdomain may host multiple roles. In this case pre-aggregation logic should respect role name specified for request or dependency.

@nizarq can shed some light on specifics. 

I'm not asking for any other dimensions. Those are special as current backend does the same already - pre-aggregates the same exact metrics for requests and dependencies on role and role instance

**Comment by macrogreg** [comment]
Thank you for clarifying, @SergeyKanzhelev .
Since Service Fabric support for per-aggregations was not intended in its initial release we should mark this issue differently than "bug". What would be an appropriate label? "Feature Request" or similar?

Overall, I absolutely agree we should support Service Fabric scenarios as soon as we can. However, since we have explicitly not done it yet, we should correctly label this tracking item.

Thanks!

**Comment by nizarq** [comment]
I would like to understand how metric pre-aggregation works. Is there a GitHub issue/discussion or something else I can look at.

**Comment by macrogreg** [comment]
There is some limited discussion here:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#trackmetric

**Comment by cijothomas** [comment]
closing as duplicate.https://github.com/microsoft/ApplicationInsights-dotnet/issues/1233
