### ISSUE TITLE
Activity ID generation breaks sampling score calculation

### ISSUE THREAD

**Issue by Dmitry-Matveev** [Microsoft/ApplicationInsights-dotnet#538]
The current way of Activity ID generation is sequential and produces quite close sampling scores:

![image](https://cloud.githubusercontent.com/assets/12158043/25057419/7b2df254-2124-11e7-8d6f-77e713a9daa1.png)

This was produced by the sample code like this:
```
            for (int i = 0; i < 1000000; i++)
            {
                Activity act = new Activity("MyOperation");
                act.Start();
                double samplingScore = (double)GetSamplingHashCode(act.Id) / int.MaxValue * 100;
                Console.WriteLine("{0}:{1}", samplingScore, act.Id);
                act.Stop();
            }
``` 
[GetSamplingHashCode](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/TelemetryChannels/ServerTelemetryChannel/Shared/Implementation/SamplingScoreGenerator.cs#L37) link.

Almost identical sampling score would mean that items are sampled out way more often then they are supposed to leading to the drop of items that would otherwise be delivered. The weight assigned to the items that are sampled in will be incorrect because actually way more items were sampled out.

**Comment by lmolkova** [comment]
The issue affects the case when root operation id is generated on the first instrumented service. 
Details about Id generation and how it works with AppInsights sampling score are described in the https://github.com/dotnet/corefx/issues/18418.

**Workaround** (until the https://github.com/dotnet/corefx/issues/18418 is resolved in Activity):
In case there was no Request-Id (x-ms-request-id) in the incoming request, feed randomly generated Id (OperationTelemetry.Id) to  the Activity (to avoid Activity's generation algorithm).

**It will work for absolute majority of the existing scenarios:**
- If multiple clients (e.g. web page) generate Id and provides it in Request-Id (x-ms-request-id) header, Id will be random even if Activity is used to generate it (since coming from different machines at different time)
- If clients do not pass Id, AppInsights will generate one from the OperationTelemetry.Id that is proven to work well with sampling

**It will not work in one corner case:**
- If between client and the first service instrumented with ApplicationInsights, there is one (or more) service that are not instrumented with AI

AND
- this service is instrumented with Activity

AND
- this service has a small number of instances

Since Activity API has been implemented a couple of months ago and package with it was released on the nuget today, and considering the other conditions, this corner case seems to almost impossible. 

**So with the workaround suggested, it does not seem to block 2.4.0-beta1 as per offline discussion with @Dmitry-Matveev**

**Activity needs to be updated to work well with hashing algorithms and the issue (https://github.com/dotnet/corefx/issues/18418) needs to be solved with the stable 2.4.0 release**

I'm going tol submit PR for dotnet-server repo with the workaround
