### ISSUE TITLE
EventFlow multi-channel support

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#559]
With the [EventFlow](https://github.com/Azure/diagnostics-eventflow) integration we enable SDK to send data to more backends than just Application Insights. Typical scenario would be send sampled and pre-aggregated data to Application Insights, ALL data to blobs or ElasticSearch and set of critical telemetry to EventHub for real-time processing.

To enable this capability we need to make a number of modifications to the SDK. The biggest change is related to configuration and initialization—to allow multiple channels, we need to somehow indicate that there can be multiple chains of TelemetryProcessors and make it easy to plug the new chain. We also want to make sure that the standard feature of Application Insights like VS experience, live stream, self-diagnostics and error reporting are not affected by this change.

We discussed with @karolz-ms there are two options - create a broadcast telemetry processor that can have multiple "children" chains or have a new concept in SDK, We agreed that the best approach will be to extend `ApplicationInsights.config` with the set of "additional channels" and keep the standard channel in place. This will ensure there is a single place to hook a new telemetry subscriber that easy to implement in external NuGet. 

The specific name of this collection is TBD. The idea is that SDK will clone the telemetry item before sending it to the channel so modification of telemetry item in a single channel will not affect another one. Every channel will have it's own set of telemetry processors

CC: @karolz-ms @Dmitry-Matveev @cijothomas @AlexBulankou

**Comment by karolz-ms** [comment]
@SergeyKanzhelev My assumption is that these "additional channels" could have their own telemetry processors and metric processors. Can you confirm?

What about telemetry initializers? I am leaning towards not including channel-specific telemetry initializers in the first iteration of this feature

**Comment by SergeyKanzhelev** [comment]
I think we got rid of MetricProcessors in latest stable. So no need to include those initially. Do you think there should be a separate concept of channel or every "additional channel" is just a `ITelemetryProcessor` that starts the chain?

**Comment by karolz-ms** [comment]
Hmm, the develop branch still has MetricProcessors on TelemetryConfiguration (internal property). Should I base this change off of different branch?

Since the primary chain is fully explorable via TelemetryConfiguration I thought it would be desirable to do the same for "additional channels". That is, I expected they will have a separate configuration-like class with processors and a telemetry channel.

**Comment by karolz-ms** [comment]
Also, do we want to have a capability for telemetry/metric processors that apply to all channels? Or do the telemetry processors that are defined at the top configuration level only applicable to the primary channel?

**Comment by SergeyKanzhelev** [comment]
it's internal. Not for public use now.

Do you think it will be hard to explain why telemetry initializers from root level will apply to all items and processors will not? Do you have a scenario when we need a root level processors (filters in reality) applicable to all channels?

**Comment by SergeyKanzhelev** [comment]
@EdPrice-MSFT, @mabsimms from the specific implementations you made - do you typically need global telemetry processors? Or per-sink processors will be enough?

Scenario we are targeting is to enable sinks listed in the picture from [this article](https://blogs.msdn.microsoft.com/azurecat/2017/05/11/azure-monitoring-and-analytics-at-scale/) by simply including Elastic Search, Graphana, etc. packages:

![image](https://cloud.githubusercontent.com/assets/9950081/26476798/f139de38-4175-11e7-9a02-6ba9dfba08e1.png)

**Comment by SergeyKanzhelev** [comment]
@karolz-ms the main features we need to maintain:
- Keep the existing behavior in case there is a third party packages which relies on current behavior
- Enable extra sinks by virtue of installing a NuGet package and 
  - applying the xdt transformation OR
  - simple in-code instruction like config.Sinks.Add()

If we implement it from scratch we'd probably keep the root level "Sink" to not overcomplicate the 99% of scenarios and make the optional list of extra sinks. Would you agree?

From that standpoint - we can imagine the `<DefaultSink>` node around `<TelemetryProcessors>` and `<TelemetryChannel>` nodes. So it become more logical that those processors only apply to that channel. I'm not sure however whether developers will appreciate those imaginary nodes =)

**Comment by karolz-ms** [comment]
@SergeyKanzhelev regarding top-level processors, since I think we agree that **having global telemetry initializers, but not global telemetry processors** strikes me as somewhat artificial limitation. So I would argue even if we did not have a good use case for the global telemetry processors, they should be included in the design for symmetry and completeness. Otherwise, sooner or later customers will find a good use case and we will get complaints about the object model limitations.

In my experience the **most common case for global processors is filtering out unnecessary data**, like you said above. This comes handy especially if you have _multiple sources of data and multiple sinks_. Sometimes it is possible to do this filtering through data source configuration, but when it is not, it makes the configuration (or initialization code) much simpler to filter out data just once, globally, before it hits the sinks. This also improves performance, because filtering is done just once.

Regarding sink configuration/initialization, I agree that having implicit root level Sink and keeping configuration simple and backward-compatible, with optional list of extra sinks, is the best way to proceed. 

I also think that it makes sense for Telemetry Processors that appear outside of `<SecondarySinks>` element (at the root level) to be treated as global, just like Telemetry Initializers that appear there. I just want to make sure that we have an answer for the **scenario where each sink has its own specific set of telemetry processors**. That is why I proposed  `NoPrimaryPipeline` property as a way to turn off the implicit AI channel and allow all sinks to be configured through `<SecondarySinks>` element.

Finally, we need to decide on a name for the "a channel plus its processors" concept. I have heard "sink" and "pipeline", both seem fine to me, we just need to decide which one it is (or maybe someone can think of an even better name).

**Comment by karolz-ms** [comment]
Another question: I am planning to implement the telemetry processor that forks the telemetry into secondary sinks as an asynchronous component. That means there is an internal queue for each sink. 

I assume we do not want to get into a situation where the queue grows indefinitely. What would be a proper way to handle the running out of queue capacity condition? E.g. throw an exception and let it bubble up to the caller of TelemetryClient.TrackXxx()?

**Comment by SergeyKanzhelev** [comment]
Ok. Naming-wise I like the idea to get consistency with [WAD](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/azure-diagnostics-configure-application-insights). MA supports upload to EH and blobs as far as I heard so this support in SDK will be aligned with overall agent/SDK direction.

W.r.t. global processors - you think about something like this:

```
<TelemetryProcessors>
  <Add Type="global filtering processor"/>
  ...
</TelemetryProcessors>

<TelemetryChannel Type= "ServerTelemetryChannel" />
<Sinks>
  <Default>
    <Add Type="Metrics pre-aggregation"
    <Add Type="Sampling"
    ...
  </Default>
  <Add Type="Blobsink" />
  <Add Type="ES sink" />
</Sinks>
```

Any existing code will still work and going forward we will be moving all processors under Sinks\Default.

Error handling - we definitely do not throw errors to the customer. We require telemetry channel to be exception free and do not catch anything in `Track` method. This enables diagnostics scenario explained [here](http://apmtips.com/blog/2016/11/10/sync-channel/). So I'd say  handle it yourself and track as `Error` in EventSource.

**Comment by karolz-ms** [comment]
Makes sense regarding error handling.

Regarding global processors, I think I like your proposal, but let me make sure we also agree about the semantic details. Taking your example as a starting point:

  1. I assume the `<TelemetryChannel Type= "ServerTelemetryChannel" />` at the top represents the channel used by the default sink?

  2. I was thinking that telemetry processors and telemetry channel will be explicitly listed under each sink. The following is meant to be semantically equivalent with your example:

```xml
<TelemetryProcessors>
  <Add Type="global filtering processor"/>
  ...
</TelemetryProcessors>

<TelemetryChannel Type= "ServerTelemetryChannel" />

<Sinks>
  <Default>
    <TelemetryProcessors>
      <Add Type="Metrics pre-aggregation" />
      <Add Type="Sampling" />
      …
    </TelemetryProcessors>
  </Default>

  <Add Name="Blobsink">
    <TelemetryProcessors>
     …
    <TelemetryProcessors>
    <TelemetryChannel Type="BlobChannel" />
  </Add>

  <Add Name="ES sink">
    <TelemetryProcessors>
      …
    </TelemetryProcessors>
    <TelemetryChannel Type="EsChannel" />
  </Add>
</Sinks>
```
This is a bit more verbose but I think the additional clarity and symmetry between top-level configuration and the sink configuration is worth it IMO.

  3. If point 2 is valid, then it would be an error for the `<TelemetryChannel>` element to appear both at the top level and under `<Default>` sink element. Placing the `<TelemetryChannel>` at the top level is supported for backward compatibility, but going forward we would place the default channel element under `<Default>` sink element, together with its processors. The top level would then be reserved for global pipeline items only (global processors and telemetry initializers).

Does this make sense?

**Comment by karolz-ms** [comment]
Ehm, @SergeyKanzhelev ?

**Comment by SergeyKanzhelev** [comment]
Yes, your proposal looks good. I do not like the `ITelemetryChannel` interface as it defines things like Developer mode and url. But do not want to introduce new interfaces

**Comment by karolz-ms** [comment]
@SergeyKanzhelev I am going to have first set of changes related to this ready for review shortly. I was wondering if you'd want to create a separate branch for me to target my PR to?

**Comment by SergeyKanzhelev** [comment]
`develop` is open for contributions.

**Comment by karolz-ms** [comment]
Small correction: because of the way configuration initialization works, I think it makes it easier to parse the configuration and also more consistent if the default sink is represented using an `<Add  Name="default">` element (using a well-known name), instead of a special `<Default>` element. So the example configuration now becomes this:

```xml
<TelemetryProcessors>
  <Add Type="global filtering processor"/>
  ...
</TelemetryProcessors>

<TelemetryChannel Type= "ServerTelemetryChannel" />

<Sinks>
  <Add Name="default">
    <TelemetryProcessors>
      <Add Type="Metrics pre-aggregation" />
      <Add Type="Sampling" />
      …
    </TelemetryProcessors>
  </Add>

  <Add Name="Blobsink">
    <TelemetryProcessors>
     …
    <TelemetryProcessors>
    <TelemetryChannel Type="BlobChannel" />
  </Add>

  <Add Name="ES sink">
    <TelemetryProcessors>
      …
    </TelemetryProcessors>
    <TelemetryChannel Type="EsChannel" />
  </Add>
</Sinks>
```

**Comment by SergeyKanzhelev** [comment]
@karolz-ms do you think you can address this https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/344#issuecomment-318408686 as part of the multi-channel support work? Not all channels require an instrumentation key at all. We just need to make sure Application Insights channels will drop items with no instrumentation key

**Comment by karolz-ms** [comment]
@SergeyKanzhelev Makes sense, I will take a look. Expect a separate PR.

**Comment by SergeyKanzhelev** [comment]
I believe this enhancement is completed. Thank you @karolz-ms!
