### ISSUE TITLE
Does .NET's Trace.CorrelationManager.ActivityId get propagated to Application Insights?

### ISSUE THREAD

**Issue by alexchantavy** [Microsoft/ApplicationInsights-dotnet#631]
I have an existing app in .NET that uses Trace Listeners with System.Diagnostics.Trace.CorrelationManager.ActivityId to correlate activities together.  I was able to route my Trace*() calls to Application Insights with no problems - super cool! - but I am unable to filter my Traces on this ActivityId.  Is there a way for me to do so?  

The [official Telemetry article](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation) acknowledges that the CorrelationManager exists, but it is unclear if ActivityId is supported out of the box.

**Comment by SergeyKanzhelev** [comment]
CC: @lmolkova

**Comment by lmolkova** [comment]
@alexchantavy 
AppInsights does not use `CorrelationManager.ActivityId`. 
Instead, it uses new concept `System.Diagnostics.Activity` for correlation. 

Since CorrelationManager.ActivityId is implemented with CallContext, it flows along with async calls and probably you can create a custom TelemetryInitializer that would set it on the telemetry.
However, we discourage you from doing this. Please use [Activity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md), it allows you to correlate your traces with any other operations tracked by AppInsights across all of your services.

**Comment by voltcode** [comment]
What's should be used for correlation, that can be used on both net core 2.2 and net FX 4.7.2?

**Comment by mikeruhl** [comment]
adding updated link from @lmolkova 's [post above](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/631#issuecomment-333182513):
[ActivityUserGuide](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md)
