### ISSUE TITLE
Custom properties on perf counters

### ISSUE THREAD

**Issue by a-vishar** [Microsoft/ApplicationInsights-dotnet#662]
I would like to be able to track perf in sessions (instead of over time).  The way we do this with other metrics is that we add a property to the metric (every submission):

`this.telemetryClient.TrackMetric(metricName, metricValue, this.metricProperties);`

metricProperties holds a property named "RunId" which we use to join multiple data streams for a dashboard.

We would ideally like to add this "RunId" as a property to the perf counters we submit through the built in `Extensibility.PerfCounterCollector` however I cannot find a way to do this.  Is this a feature that has a milestone attached or is there a workaround?

Many thanks.

**Comment by MS-TimothyMothra** [comment]
Hi @a-vishar,
You can implement a custom TelemetryInitializer to easily append properties to telemetry.
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer

I don't have a recommendation on exposing your RunId to the initializer.
Something to consider: I assume this is a Web App where you might have multiple consecutive RunIds. Because PerfCounters represent your hosted environment, it might not make sense to append an individual RunId to a PerfCounter.
