### ISSUE TITLE
Tracking ClientPerformance documents using .Net SDK

### ISSUE THREAD

**Issue by yanivid3** [microsoft/ApplicationInsights-dotnet#673]
Hi,

For our E2E monitoring flow, we would like to be able to use the .Net SDK to track ClientPerformance (PageViewPerf) documents.
Will appreciate if supporting this document type can be added to the .Net SDK so I track such documents using the TelemetryClient.

Thanks,
Yaniv

**Comment by SergeyKanzhelev** [comment]
I was thinking of scenario - proxying JS telemetry thru the application instead of sending to Application Insights endpoint directly. This way application can avoid exposing instrumentation key and apply extra auth for telemetry. 

In order to implement this scenario we will need PageViewPerfoamance type as well as ability to restore `ExceptionTelemetry` without the exception object itself (issue tracked separately).

**Comment by MS-TimothyMothra** [comment]
I like this idea..
I think our Web API could inject a virtual controller (ApplicationInsightsTelemetryController) to receive telemetry from the client and pass through to our TelemetryChannel. 

This would be a fun project :)
