### ISSUE TITLE
Enable sampling for Custom Performance Counters

### ISSUE THREAD

**Issue by garamamo** [Microsoft/ApplicationInsights-dotnet#713]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. 
Create a PerformanceCollectorModule and initialize it with TelemetryConfiguration.Active.
2.
Add PerformanceCounters by PerformanceCollectorModule.Add(new PerformanceCounterCollectionRequest("\Processor(_Total)\% Processor Time", "% Total Processor Time")) //Note: You can add any counter here.
3.
Run steps 1 and 2 in a loop or add the same counter request in step 2 multiple times

##  Actual Behavior
The counter reports to AI multiple times in a very short time (even once every ms depending upon the loop). Try ingestion sampling or adaptive sampling to control the data ingestion in App Insights. It does not work.

## Expected Behavior
Perf counters or atleast custom perf counters should be subject to sampling.

## Version Info 
SDK Version : Microsoft.ApplicationInsights.AspNetCore (2.2.0-beta3)
.NET Version : net470	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Windows Azure
Hosting Info (IIS/Azure WebApps/ etc) : Service Fabric

**Comment by cijothomas** [comment]
Application Insights does not sample metrics and sessions telemetry types. Reduction in the precision can be highly undesirable for these telemetry types.  This is by design.
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-sampling

**Comment by d3r3kk** [comment]
I think the intent of this issue is to raise the idea that we might be able to throttle perf counters that are ingested and stored, rather than ingested and used for transient UX elements such as Live Metrics Data. The issue arose for this customer when a lot of perf counter data started clobbering his quota over the course of a day.

The way I understand it is that perf counter data is necessary for Live Metrics Streams as often as possible (depending on the counter of course), but whittling down the actual ingested perf counter data stored would only have an effect on historic data - much the same that any throttling has on other telemetry.

**Comment by SergeyKanzhelev** [comment]
>The way I understand it is that perf counter data is necessary for Live Metrics Streams as often as possible (depending on the counter of course), but whittling down the actual ingested perf counter data stored would only have an effect on historic data - much the same that any throttling has on other telemetry.

Live metrics counters collected using alternative approach. Those counters are not sent to the paid backend

**Comment by d3r3kk** [comment]
Understood, then perf counters _could_ be filtered, no? Or would doing so affect both Live Metrics Streams as well as ingested+stored data?
