### ISSUE TITLE
Instrumentation Key null even though applicationinsights.config is present

### ISSUE THREAD

**Issue by kleky** [Microsoft/ApplicationInsights-dotnet#714]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Created console application
2. Added:

Install-Package Microsoft.ApplicationInsights  
Install-Package Microsoft.ApplicationInsights.WindowsServer  
Install-Package Microsoft.ApplicationInsights.Web 

3. Added to applicationinsight.config file with instrumentation key

<InstrumentationKey>xxxxx-xxx-xx-xx</InstrumentationKey>

4. add code: TelemetryClient telemetryClient = new TelemetryClient();

##  Actual Behavior
run program in debug to find telemetryClient  instrumentation key always null.

## Expected Behavior
run program in debug to find telemetryClient  instrumentation key populated same as in .config.

## Version Info 
Visual Studio 2017
.NET Version :	4.5.2 						
OS : Windows 10

**Comment by MS-TimothyMothra** [comment]
Hi @kleky, 
Can you please tell me which version of the SDK you're using?

Just to rule out some of the easy stuff:

- Can you confirm that the XML is formatted correctly:
Should check the position, spelling and closing tag.
```
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
    <InstrumentationKey>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</InstrumentationKey>
</ApplicationInsights>
```

- Something else I've seen before, where the config file isn't being deployed correctly.. 
Can you please confirm that the config is in the root of your bin directory and contains your changes?

Thanks

**Comment by kleky** [comment]
@MS-TimothyMothra  thanks for reply.

SDK version is 4.7.02556.

XML formatted the same as you posted, but still nothing - I also made sure that the config file was in the bin directory with my changes.

**Comment by MS-TimothyMothra** [comment]
@kleky hmmm, that can't be right.
Microsoft.ApplicationInsights.Web is only up to 2.5.1 ([Nuget](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/))

- Are you using Net Framework 4.7 perhaps?
- Just to be clear, is your project a dotnet Asp project, and not Net Core? I ask because the configuration is different.

So you're not blocked, you have the option to set the ikey at runtime as a workaround:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-configuration-with-applicationinsights-config#instrumentationkey

**Comment by pharring** [comment]
If TelemetryClient.InstrumentationKey is null, then the instrumentation key will be picked up from the TelemetryConfguration. If _that_ is null, then the channel will be "unconfigured".
