### ISSUE TITLE
Clean up the story with TrackMetric method

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#919]
See http://dajbych.net/why-is-the-application-insights-trackmetric-method-missing for feedback.

There should be a supported way to report an aggregated metric to Application Insights. It may be called differently, but it should exist.

Either `TrackMetric` should clearly indicate that it is about aggregated metric or the method with new name should be introduced.

**Comment by EnCey** [comment]
Please mark the method with [`[Obsolete]`](https://docs.microsoft.com/en-ie/dotnet/api/system.obsoleteattribute?view=netframework-4.7.2) if it is deprecated. 

Back-and-forth discussions are one thing, not using `Obsolete` in favour of XML docs and IntelliSense meddling is quite another. It's like changing the font colour to white instead of deleting something, completely mind boggling. I'd rather learn about a deprecated method in my code base via a compiler warning than having to stumble across it in the docs months later.

**Comment by Dmitry-Matveev** [comment]
@EnCey, I agree that this is a confusing end result that does not come in hand with the best practices, @SergeyKanzhelev / @macrogreg are ironing the whole story out and will fix the markings along the way. Thanks for reporting!

**Comment by cijothomas** [comment]
Fixed with #1153
