### ISSUE TITLE
Missing stacktrace of inner exceptions in Service Fabric project

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#922]
Moved from: https://github.com/Microsoft/ApplicationInsights-Home/issues/264

Reported by: @gemas

We have a Service Fabric application. Existing out of an WebAPI and a Stateless Service.

When the WebAPI does a remote call to the Stateless Service and an Exception is thrown in the Service we catch this in the WebAPI.
While debugging we inspect this exception in the WebAPI, we see the Exception contains a lot of inner exceptions, the lowest one containing the stacktrace of the Service.
When we call the function TrackException(ex) the exception is logged in Application insights.
But the stacktraces of the inner exceptions are not.
So we dont know where it went wrong.

We use version 2.7.2 of ApplicationInsights

**Comment by SergeyKanzhelev** [comment]
It looks like other tools account for both - local stack trace as well as remote stack trace stored as a string in Exception object in variable `_remoteStackTraceString;`. Application Insights doesn't implement this logic. Workaround it to get this stack trace in code and store into exception telemetry properties before calling `TrackException`.

I marked issue as enhancement. We welcome contributions if you willing to help here.

**Comment by tijntje** [comment]
I have the same issue; 

For me this doesn't look like an enhancement but a bug.
This bug makes the use of Application insights in a service fabric project very limited because you only have a stacktrace until the remoting. 

We had to write a custom ExceptionFilter as a workaround.

Can this be flagged as bug?

**Comment by pharring** [comment]
You could try using the Snapshot Debugger. Snapshots will contain full information about the exception including the remote stack trace (if any).
Alternatively (or additionally), make sure your calls between services are correlated and that the stateless service also calls TrackException. I can't recall if the Service Fabric SDK automatically correlates cross-service remoting calls.

**Comment by tijntje** [comment]
The problem with logging from within the services is that you will log also exceptions that are transient, and or expected. Correlating is added by AppInsights service fabric package; App insights is also not logging transient errors, so really, the only missing thing is the missing stacktrace.

**Comment by pharring** [comment]
@tijntje Can you explain what you mean by 'transient' exceptions or errors? My understanding is that transient errors can be handled with a retry, but I have a feeling you mean something else.

If an exception goes unhandled in a remote call, ending up in the remoting code, that seems like something that could be logged. I would expect the App Insights Service Fabric package to already do that - but I haven't looked at the code.

**Comment by SergeyKanzhelev** [comment]
thanks for upvote. I still think it's enhancement as impact is scoped very narrowly. 

@yantang-msft, @brahmnes, @pharring can you look into what @pharring said. Will the use of ServiceFabric package work around this issue? If not - can you help with the fix as this is mostly for ServiceFabric apps?

**Comment by yantang-msft** [comment]
Sorry for the late reply, this issue slipped off my radar for quite a while.
The problem is within the StackTrace library used at [here](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/39a5ef23d834777eefdd72149de705a016eb06b0/src/Microsoft.ApplicationInsights/Extensibility/Implementation/ExceptionConverter.cs#L21). Basically for the remote exception, after calling the StackTrace converter, it doesn't parse the stack trace correctly and returns an empty list. So it's neither an issue with SF.AI or AI dotnet package.
I suspect it's because of the string format of the remoting exception. I'll create an issue in the netcore repo with more details.

**Comment by juho-hanhimaki** [comment]
Any chance this gets looked at? Pretty much makes Application Insights with Service Fabric useless for us.

.NET Core folks seem to think this should be fixed in Application Insights instead of StackTrace library:

> > Is it a bug or expected?
> 
> This is expected and it is unlikely to be fixed. The remote stack trace is opaque string. The local process is often not going to have the right metadata to populate `StackFrame.GetMethod()` property.
> 
> @yantang-msft I would recommend for Application Insights to use an alternative mechanism for parsing remote stack traces that does not depend on `StackFrame` types.
> 
> _Originally posted by @jkotas in https://github.com/dotnet/corefx/issues/34592#issuecomment-492701377_
